<?php
// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

// <auto-generated>
//
// Generated from file `ClientInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


if(!class_exists('LbaNet_WorldDesc'))
{
    class LbaNet_WorldDesc
    {
        public function __construct($WorldName='', $Description='', $News='', $DataDirPath='')
        {
            $this->WorldName = $WorldName;
            $this->Description = $Description;
            $this->News = $News;
            $this->DataDirPath = $DataDirPath;
        }

        public function __toString()
        {
            global $LbaNet__t_WorldDesc;
            return IcePHP_stringify($this, $LbaNet__t_WorldDesc);
        }

        public $WorldName;
        public $Description;
        public $News;
        public $DataDirPath;
    }

    $LbaNet__t_WorldDesc = IcePHP_defineStruct('::LbaNet::WorldDesc', 'LbaNet_WorldDesc', array(
        array('WorldName', $IcePHP__t_string), 
        array('Description', $IcePHP__t_string), 
        array('News', $IcePHP__t_string), 
        array('DataDirPath', $IcePHP__t_string)));
}

if(!isset($LbaNet__t_WorldsSeq))
{
    $LbaNet__t_WorldsSeq = IcePHP_defineSequence('::LbaNet::WorldsSeq', $LbaNet__t_WorldDesc);
}

if(!class_exists('LbaNet_FriendInfo'))
{
    class LbaNet_FriendInfo
    {
        public function __construct($Id=0, $Pending=false, $ToAccept=false, $Name='', $Removed=false)
        {
            $this->Id = $Id;
            $this->Pending = $Pending;
            $this->ToAccept = $ToAccept;
            $this->Name = $Name;
            $this->Removed = $Removed;
        }

        public function __toString()
        {
            global $LbaNet__t_FriendInfo;
            return IcePHP_stringify($this, $LbaNet__t_FriendInfo);
        }

        public $Id;
        public $Pending;
        public $ToAccept;
        public $Name;
        public $Removed;
    }

    $LbaNet__t_FriendInfo = IcePHP_defineStruct('::LbaNet::FriendInfo', 'LbaNet_FriendInfo', array(
        array('Id', $IcePHP__t_long), 
        array('Pending', $IcePHP__t_bool), 
        array('ToAccept', $IcePHP__t_bool), 
        array('Name', $IcePHP__t_string), 
        array('Removed', $IcePHP__t_bool)));
}

if(!isset($LbaNet__t_FriendsSeq))
{
    $LbaNet__t_FriendsSeq = IcePHP_defineSequence('::LbaNet::FriendsSeq', $LbaNet__t_FriendInfo);
}

if(!class_exists('LbaNet_PMInfo'))
{
    class LbaNet_PMInfo
    {
        public function __construct($PMId=0, $ReplyId=0, $FromName='', $ToName='', $Text='', $Opened=false, $Date='')
        {
            $this->PMId = $PMId;
            $this->ReplyId = $ReplyId;
            $this->FromName = $FromName;
            $this->ToName = $ToName;
            $this->Text = $Text;
            $this->Opened = $Opened;
            $this->Date = $Date;
        }

        public function __toString()
        {
            global $LbaNet__t_PMInfo;
            return IcePHP_stringify($this, $LbaNet__t_PMInfo);
        }

        public $PMId;
        public $ReplyId;
        public $FromName;
        public $ToName;
        public $Text;
        public $Opened;
        public $Date;
    }

    $LbaNet__t_PMInfo = IcePHP_defineStruct('::LbaNet::PMInfo', 'LbaNet_PMInfo', array(
        array('PMId', $IcePHP__t_long), 
        array('ReplyId', $IcePHP__t_long), 
        array('FromName', $IcePHP__t_string), 
        array('ToName', $IcePHP__t_string), 
        array('Text', $IcePHP__t_string), 
        array('Opened', $IcePHP__t_bool), 
        array('Date', $IcePHP__t_string)));
}

if(!isset($LbaNet__t_PMsSeq))
{
    $LbaNet__t_PMsSeq = IcePHP_defineSequence('::LbaNet::PMsSeq', $LbaNet__t_PMInfo);
}

if(!class_exists('LbaNet_ItemInfo'))
{
    class LbaNet_ItemInfo
    {
        public function __construct($Id=0, $IconName='', $DescriptionId=0, $Count=0, $Max=0, $Price=0, $DescriptionTextExtra='', $Position=0)
        {
            $this->Id = $Id;
            $this->IconName = $IconName;
            $this->DescriptionId = $DescriptionId;
            $this->Count = $Count;
            $this->Max = $Max;
            $this->Price = $Price;
            $this->DescriptionTextExtra = $DescriptionTextExtra;
            $this->Position = $Position;
        }

        public function __toString()
        {
            global $LbaNet__t_ItemInfo;
            return IcePHP_stringify($this, $LbaNet__t_ItemInfo);
        }

        public $Id;
        public $IconName;
        public $DescriptionId;
        public $Count;
        public $Max;
        public $Price;
        public $DescriptionTextExtra;
        public $Position;
    }

    $LbaNet__t_ItemInfo = IcePHP_defineStruct('::LbaNet::ItemInfo', 'LbaNet_ItemInfo', array(
        array('Id', $IcePHP__t_long), 
        array('IconName', $IcePHP__t_string), 
        array('DescriptionId', $IcePHP__t_long), 
        array('Count', $IcePHP__t_int), 
        array('Max', $IcePHP__t_int), 
        array('Price', $IcePHP__t_int), 
        array('DescriptionTextExtra', $IcePHP__t_string), 
        array('Position', $IcePHP__t_int)));
}

if(!isset($LbaNet__t_ItemsMap))
{
    $LbaNet__t_ItemsMap = IcePHP_defineDictionary('::LbaNet::ItemsMap', $IcePHP__t_long, $LbaNet__t_ItemInfo);
}

if(!isset($LbaNet__t_ItemList))
{
    $LbaNet__t_ItemList = IcePHP_defineDictionary('::LbaNet::ItemList', $IcePHP__t_long, $IcePHP__t_int);
}

if(!class_exists('LbaNet_PlayerOnline'))
{
    class LbaNet_PlayerOnline
    {
        public function __construct($Joined=false, $Nickname='', $Status='', $Color='')
        {
            $this->Joined = $Joined;
            $this->Nickname = $Nickname;
            $this->Status = $Status;
            $this->Color = $Color;
        }

        public function __toString()
        {
            global $LbaNet__t_PlayerOnline;
            return IcePHP_stringify($this, $LbaNet__t_PlayerOnline);
        }

        public $Joined;
        public $Nickname;
        public $Status;
        public $Color;
    }

    $LbaNet__t_PlayerOnline = IcePHP_defineStruct('::LbaNet::PlayerOnline', 'LbaNet_PlayerOnline', array(
        array('Joined', $IcePHP__t_bool), 
        array('Nickname', $IcePHP__t_string), 
        array('Status', $IcePHP__t_string), 
        array('Color', $IcePHP__t_string)));
}

if(!isset($LbaNet__t_PlayerOnlinesSeq))
{
    $LbaNet__t_PlayerOnlinesSeq = IcePHP_defineSequence('::LbaNet::PlayerOnlinesSeq', $LbaNet__t_PlayerOnline);
}

if(!isset($LbaNet__t_TeleportsSeq))
{
    $LbaNet__t_TeleportsSeq = IcePHP_defineSequence('::LbaNet::TeleportsSeq', $IcePHP__t_string);
}

if(!isset($LbaNet__t_ShortcutsSeq))
{
    $LbaNet__t_ShortcutsSeq = IcePHP_defineSequence('::LbaNet::ShortcutsSeq', $LbaNet__t_ItemInfo);
}

if(!class_exists('LbaNet_LetterInfo'))
{
    class LbaNet_LetterInfo
    {
        public function __construct($LetterId=0, $Date='', $From='', $Subject='', $Message='')
        {
            $this->LetterId = $LetterId;
            $this->Date = $Date;
            $this->From = $From;
            $this->Subject = $Subject;
            $this->Message = $Message;
        }

        public function __toString()
        {
            global $LbaNet__t_LetterInfo;
            return IcePHP_stringify($this, $LbaNet__t_LetterInfo);
        }

        public $LetterId;
        public $Date;
        public $From;
        public $Subject;
        public $Message;
    }

    $LbaNet__t_LetterInfo = IcePHP_defineStruct('::LbaNet::LetterInfo', 'LbaNet_LetterInfo', array(
        array('LetterId', $IcePHP__t_long), 
        array('Date', $IcePHP__t_string), 
        array('From', $IcePHP__t_string), 
        array('Subject', $IcePHP__t_string), 
        array('Message', $IcePHP__t_string)));
}

if(!class_exists('LbaNet_QuestInfo'))
{
    class LbaNet_QuestInfo
    {
        public function __construct($Id=0, $ChapterTextId=0, $QuestAreaTextId=0, $TittleTextId=0, $DescriptionTextId=0, $Visible=false)
        {
            $this->Id = $Id;
            $this->ChapterTextId = $ChapterTextId;
            $this->QuestAreaTextId = $QuestAreaTextId;
            $this->TittleTextId = $TittleTextId;
            $this->DescriptionTextId = $DescriptionTextId;
            $this->Visible = $Visible;
        }

        public function __toString()
        {
            global $LbaNet__t_QuestInfo;
            return IcePHP_stringify($this, $LbaNet__t_QuestInfo);
        }

        public $Id;
        public $ChapterTextId;
        public $QuestAreaTextId;
        public $TittleTextId;
        public $DescriptionTextId;
        public $Visible;
    }

    $LbaNet__t_QuestInfo = IcePHP_defineStruct('::LbaNet::QuestInfo', 'LbaNet_QuestInfo', array(
        array('Id', $IcePHP__t_long), 
        array('ChapterTextId', $IcePHP__t_long), 
        array('QuestAreaTextId', $IcePHP__t_long), 
        array('TittleTextId', $IcePHP__t_long), 
        array('DescriptionTextId', $IcePHP__t_long), 
        array('Visible', $IcePHP__t_bool)));
}

if(!isset($LbaNet__t_QuestsMap))
{
    $LbaNet__t_QuestsMap = IcePHP_defineDictionary('::LbaNet::QuestsMap', $IcePHP__t_long, $LbaNet__t_QuestInfo);
}

if(!isset($LbaNet__t_PlayerChoicesSeq))
{
    $LbaNet__t_PlayerChoicesSeq = IcePHP_defineSequence('::LbaNet::PlayerChoicesSeq', $IcePHP__t_long);
}

if(!class_exists('LbaNet_DialogPartInfo'))
{
    class LbaNet_DialogPartInfo
    {
        public function __construct($NpcTextId=0, $PlayerTextsId=null)
        {
            $this->NpcTextId = $NpcTextId;
            $this->PlayerTextsId = $PlayerTextsId;
        }

        public function __toString()
        {
            global $LbaNet__t_DialogPartInfo;
            return IcePHP_stringify($this, $LbaNet__t_DialogPartInfo);
        }

        public $NpcTextId;
        public $PlayerTextsId;
    }

    $LbaNet__t_DialogPartInfo = IcePHP_defineStruct('::LbaNet::DialogPartInfo', 'LbaNet_DialogPartInfo', array(
        array('NpcTextId', $IcePHP__t_long), 
        array('PlayerTextsId', $LbaNet__t_PlayerChoicesSeq)));
}

if(!class_exists('LbaNet_PlayerInfo'))
{
    class LbaNet_PlayerInfo
    {
        public function __construct($Id=0, $Status='', $NameColor='')
        {
            $this->Id = $Id;
            $this->Status = $Status;
            $this->NameColor = $NameColor;
        }

        public function __toString()
        {
            global $LbaNet__t_PlayerInfo;
            return IcePHP_stringify($this, $LbaNet__t_PlayerInfo);
        }

        public $Id;
        public $Status;
        public $NameColor;
    }

    $LbaNet__t_PlayerInfo = IcePHP_defineStruct('::LbaNet::PlayerInfo', 'LbaNet_PlayerInfo', array(
        array('Id', $IcePHP__t_long), 
        array('Status', $IcePHP__t_string), 
        array('NameColor', $IcePHP__t_string)));
}

if(!isset($LbaNet__t_ConnectedL))
{
    $LbaNet__t_ConnectedL = IcePHP_defineDictionary('::LbaNet::ConnectedL', $IcePHP__t_string, $LbaNet__t_PlayerInfo);
}

if(!class_exists('LbaNet_GuiParameterBase'))
{
    class LbaNet_GuiParameterBase extends Ice_ObjectImpl
    {
        public function __construct()
        {
        }

        public static function ice_staticId()
        {
            return '::LbaNet::GuiParameterBase';
        }

        public function __toString()
        {
            global $LbaNet__t_GuiParameterBase;
            return IcePHP_stringify($this, $LbaNet__t_GuiParameterBase);
        }
    }

    class LbaNet_GuiParameterBasePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::GuiParameterBase', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::GuiParameterBase', $facet);
        }
    }

    $LbaNet__t_GuiParameterBase = IcePHP_defineClass('::LbaNet::GuiParameterBase', 'LbaNet_GuiParameterBase', false, $Ice__t_Object, null, null);

    $LbaNet__t_GuiParameterBasePrx = IcePHP_defineProxy($LbaNet__t_GuiParameterBase);
}

if(!isset($LbaNet__t_GuiParamsSeq))
{
    $LbaNet__t_GuiParamsSeq = IcePHP_defineSequence('::LbaNet::GuiParamsSeq', $LbaNet__t_GuiParameterBase);
}

if(!class_exists('LbaNet_InventoryGuiParameter'))
{
    class LbaNet_InventoryGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($InventorySize=0, $InventoryContent=null)
        {
            parent::__construct();
            $this->InventorySize = $InventorySize;
            $this->InventoryContent = $InventoryContent;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::InventoryGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_InventoryGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_InventoryGuiParameter);
        }

        public $InventorySize;
        public $InventoryContent;
    }

    class LbaNet_InventoryGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::InventoryGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::InventoryGuiParameter', $facet);
        }
    }

    $LbaNet__t_InventoryGuiParameter = IcePHP_defineClass('::LbaNet::InventoryGuiParameter', 'LbaNet_InventoryGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('InventorySize', $IcePHP__t_int),
    
        array('InventoryContent', $LbaNet__t_ItemsMap)));

    $LbaNet__t_InventoryGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_InventoryGuiParameter);
}

if(!class_exists('LbaNet_ContainerGuiParameter'))
{
    class LbaNet_ContainerGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($ContainerId=0, $InventorySize=0, $ContainerContent=null, $InventoryContent=null)
        {
            parent::__construct();
            $this->ContainerId = $ContainerId;
            $this->InventorySize = $InventorySize;
            $this->ContainerContent = $ContainerContent;
            $this->InventoryContent = $InventoryContent;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ContainerGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_ContainerGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_ContainerGuiParameter);
        }

        public $ContainerId;
        public $InventorySize;
        public $ContainerContent;
        public $InventoryContent;
    }

    class LbaNet_ContainerGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ContainerGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ContainerGuiParameter', $facet);
        }
    }

    $LbaNet__t_ContainerGuiParameter = IcePHP_defineClass('::LbaNet::ContainerGuiParameter', 'LbaNet_ContainerGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('ContainerId', $IcePHP__t_long),
    
        array('InventorySize', $IcePHP__t_int),
    
        array('ContainerContent', $LbaNet__t_ItemsMap),
    
        array('InventoryContent', $LbaNet__t_ItemsMap)));

    $LbaNet__t_ContainerGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_ContainerGuiParameter);
}

if(!class_exists('LbaNet_ShopGuiParameter'))
{
    class LbaNet_ShopGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($NPCId=0, $ShopContent=null, $MoneyIconName='')
        {
            parent::__construct();
            $this->NPCId = $NPCId;
            $this->ShopContent = $ShopContent;
            $this->MoneyIconName = $MoneyIconName;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ShopGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_ShopGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_ShopGuiParameter);
        }

        public $NPCId;
        public $ShopContent;
        public $MoneyIconName;
    }

    class LbaNet_ShopGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ShopGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ShopGuiParameter', $facet);
        }
    }

    $LbaNet__t_ShopGuiParameter = IcePHP_defineClass('::LbaNet::ShopGuiParameter', 'LbaNet_ShopGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('NPCId', $IcePHP__t_long),
    
        array('ShopContent', $LbaNet__t_ItemsMap),
    
        array('MoneyIconName', $IcePHP__t_string)));

    $LbaNet__t_ShopGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_ShopGuiParameter);
}

if(!class_exists('LbaNet_MailboxGuiParameter'))
{
    class LbaNet_MailboxGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($MailboxContent=null)
        {
            parent::__construct();
            $this->MailboxContent = $MailboxContent;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::MailboxGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_MailboxGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_MailboxGuiParameter);
        }

        public $MailboxContent;
    }

    class LbaNet_MailboxGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::MailboxGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::MailboxGuiParameter', $facet);
        }
    }

    $LbaNet__t_MailboxGuiParameter = IcePHP_defineClass('::LbaNet::MailboxGuiParameter', 'LbaNet_MailboxGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('MailboxContent', $LbaNet__t_PMsSeq)));

    $LbaNet__t_MailboxGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_MailboxGuiParameter);
}

if(!class_exists('LbaNet_FriendListGuiParameter'))
{
    class LbaNet_FriendListGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($FriendList=null)
        {
            parent::__construct();
            $this->FriendList = $FriendList;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::FriendListGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_FriendListGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_FriendListGuiParameter);
        }

        public $FriendList;
    }

    class LbaNet_FriendListGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::FriendListGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::FriendListGuiParameter', $facet);
        }
    }

    $LbaNet__t_FriendListGuiParameter = IcePHP_defineClass('::LbaNet::FriendListGuiParameter', 'LbaNet_FriendListGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('FriendList', $LbaNet__t_FriendsSeq)));

    $LbaNet__t_FriendListGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_FriendListGuiParameter);
}

if(!class_exists('LbaNet_PlayerOnlineListGuiParameter'))
{
    class LbaNet_PlayerOnlineListGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($PlayerList=null)
        {
            parent::__construct();
            $this->PlayerList = $PlayerList;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::PlayerOnlineListGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_PlayerOnlineListGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_PlayerOnlineListGuiParameter);
        }

        public $PlayerList;
    }

    class LbaNet_PlayerOnlineListGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::PlayerOnlineListGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::PlayerOnlineListGuiParameter', $facet);
        }
    }

    $LbaNet__t_PlayerOnlineListGuiParameter = IcePHP_defineClass('::LbaNet::PlayerOnlineListGuiParameter', 'LbaNet_PlayerOnlineListGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('PlayerList', $LbaNet__t_PlayerOnlinesSeq)));

    $LbaNet__t_PlayerOnlineListGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_PlayerOnlineListGuiParameter);
}

if(!class_exists('LbaNet_TeleportGuiParameter'))
{
    class LbaNet_TeleportGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($TeleportList=null)
        {
            parent::__construct();
            $this->TeleportList = $TeleportList;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::TeleportGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_TeleportGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_TeleportGuiParameter);
        }

        public $TeleportList;
    }

    class LbaNet_TeleportGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::TeleportGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::TeleportGuiParameter', $facet);
        }
    }

    $LbaNet__t_TeleportGuiParameter = IcePHP_defineClass('::LbaNet::TeleportGuiParameter', 'LbaNet_TeleportGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('TeleportList', $LbaNet__t_TeleportsSeq)));

    $LbaNet__t_TeleportGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_TeleportGuiParameter);
}

if(!class_exists('LbaNet_ShortcutGuiParameter'))
{
    class LbaNet_ShortcutGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($ShorcutList=null)
        {
            parent::__construct();
            $this->ShorcutList = $ShorcutList;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ShortcutGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_ShortcutGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_ShortcutGuiParameter);
        }

        public $ShorcutList;
    }

    class LbaNet_ShortcutGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ShortcutGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ShortcutGuiParameter', $facet);
        }
    }

    $LbaNet__t_ShortcutGuiParameter = IcePHP_defineClass('::LbaNet::ShortcutGuiParameter', 'LbaNet_ShortcutGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('ShorcutList', $LbaNet__t_ShortcutsSeq)));

    $LbaNet__t_ShortcutGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_ShortcutGuiParameter);
}

if(!class_exists('LbaNet_LetterViewerGuiParameter'))
{
    class LbaNet_LetterViewerGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($ToDisplayInfo=null)
        {
            parent::__construct();
            $this->ToDisplayInfo = is_null($ToDisplayInfo) ? new LbaNet_LetterInfo : $ToDisplayInfo;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::LetterViewerGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_LetterViewerGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_LetterViewerGuiParameter);
        }

        public $ToDisplayInfo;
    }

    class LbaNet_LetterViewerGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::LetterViewerGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::LetterViewerGuiParameter', $facet);
        }
    }

    $LbaNet__t_LetterViewerGuiParameter = IcePHP_defineClass('::LbaNet::LetterViewerGuiParameter', 'LbaNet_LetterViewerGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('ToDisplayInfo', $LbaNet__t_LetterInfo)));

    $LbaNet__t_LetterViewerGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_LetterViewerGuiParameter);
}

if(!class_exists('LbaNet_QuestJournalGuiParameter'))
{
    class LbaNet_QuestJournalGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($QuestsStarted=null, $QuestsFinished=null)
        {
            parent::__construct();
            $this->QuestsStarted = $QuestsStarted;
            $this->QuestsFinished = $QuestsFinished;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::QuestJournalGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_QuestJournalGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_QuestJournalGuiParameter);
        }

        public $QuestsStarted;
        public $QuestsFinished;
    }

    class LbaNet_QuestJournalGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::QuestJournalGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::QuestJournalGuiParameter', $facet);
        }
    }

    $LbaNet__t_QuestJournalGuiParameter = IcePHP_defineClass('::LbaNet::QuestJournalGuiParameter', 'LbaNet_QuestJournalGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('QuestsStarted', $LbaNet__t_QuestsMap),
    
        array('QuestsFinished', $LbaNet__t_QuestsMap)));

    $LbaNet__t_QuestJournalGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_QuestJournalGuiParameter);
}

if(!class_exists('LbaNet_DialogGuiParameter'))
{
    class LbaNet_DialogGuiParameter extends LbaNet_GuiParameterBase
    {
        public function __construct($NPCId=0, $TittleTextId=0, $DialogPart=null)
        {
            parent::__construct();
            $this->NPCId = $NPCId;
            $this->TittleTextId = $TittleTextId;
            $this->DialogPart = is_null($DialogPart) ? new LbaNet_DialogPartInfo : $DialogPart;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::DialogGuiParameter';
        }

        public function __toString()
        {
            global $LbaNet__t_DialogGuiParameter;
            return IcePHP_stringify($this, $LbaNet__t_DialogGuiParameter);
        }

        public $NPCId;
        public $TittleTextId;
        public $DialogPart;
    }

    class LbaNet_DialogGuiParameterPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::DialogGuiParameter', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::DialogGuiParameter', $facet);
        }
    }

    $LbaNet__t_DialogGuiParameter = IcePHP_defineClass('::LbaNet::DialogGuiParameter', 'LbaNet_DialogGuiParameter', false, $LbaNet__t_GuiParameterBase, null, array(
        array('NPCId', $IcePHP__t_long),
    
        array('TittleTextId', $IcePHP__t_long),
    
        array('DialogPart', $LbaNet__t_DialogPartInfo)));

    $LbaNet__t_DialogGuiParameterPrx = IcePHP_defineProxy($LbaNet__t_DialogGuiParameter);
}

if(!class_exists('LbaNet_GuiUpdateBase'))
{
    class LbaNet_GuiUpdateBase extends Ice_ObjectImpl
    {
        public function __construct()
        {
        }

        public static function ice_staticId()
        {
            return '::LbaNet::GuiUpdateBase';
        }

        public function __toString()
        {
            global $LbaNet__t_GuiUpdateBase;
            return IcePHP_stringify($this, $LbaNet__t_GuiUpdateBase);
        }
    }

    class LbaNet_GuiUpdateBasePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::GuiUpdateBase', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::GuiUpdateBase', $facet);
        }
    }

    $LbaNet__t_GuiUpdateBase = IcePHP_defineClass('::LbaNet::GuiUpdateBase', 'LbaNet_GuiUpdateBase', false, $Ice__t_Object, null, null);

    $LbaNet__t_GuiUpdateBasePrx = IcePHP_defineProxy($LbaNet__t_GuiUpdateBase);
}

if(!isset($LbaNet__t_GuiUpdatesSeq))
{
    $LbaNet__t_GuiUpdatesSeq = IcePHP_defineSequence('::LbaNet::GuiUpdatesSeq', $LbaNet__t_GuiUpdateBase);
}

if(!class_exists('LbaNet_AddFriend'))
{
    class LbaNet_AddFriend extends LbaNet_GuiUpdateBase
    {
        public function __construct($FriendName='')
        {
            parent::__construct();
            $this->FriendName = $FriendName;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::AddFriend';
        }

        public function __toString()
        {
            global $LbaNet__t_AddFriend;
            return IcePHP_stringify($this, $LbaNet__t_AddFriend);
        }

        public $FriendName;
    }

    class LbaNet_AddFriendPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::AddFriend', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::AddFriend', $facet);
        }
    }

    $LbaNet__t_AddFriend = IcePHP_defineClass('::LbaNet::AddFriend', 'LbaNet_AddFriend', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('FriendName', $IcePHP__t_string)));

    $LbaNet__t_AddFriendPrx = IcePHP_defineProxy($LbaNet__t_AddFriend);
}

if(!class_exists('LbaNet_AcceptFriend'))
{
    class LbaNet_AcceptFriend extends LbaNet_GuiUpdateBase
    {
        public function __construct($FriendId=0)
        {
            parent::__construct();
            $this->FriendId = $FriendId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::AcceptFriend';
        }

        public function __toString()
        {
            global $LbaNet__t_AcceptFriend;
            return IcePHP_stringify($this, $LbaNet__t_AcceptFriend);
        }

        public $FriendId;
    }

    class LbaNet_AcceptFriendPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::AcceptFriend', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::AcceptFriend', $facet);
        }
    }

    $LbaNet__t_AcceptFriend = IcePHP_defineClass('::LbaNet::AcceptFriend', 'LbaNet_AcceptFriend', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('FriendId', $IcePHP__t_long)));

    $LbaNet__t_AcceptFriendPrx = IcePHP_defineProxy($LbaNet__t_AcceptFriend);
}

if(!class_exists('LbaNet_RemoveFriend'))
{
    class LbaNet_RemoveFriend extends LbaNet_GuiUpdateBase
    {
        public function __construct($FriendId=0)
        {
            parent::__construct();
            $this->FriendId = $FriendId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::RemoveFriend';
        }

        public function __toString()
        {
            global $LbaNet__t_RemoveFriend;
            return IcePHP_stringify($this, $LbaNet__t_RemoveFriend);
        }

        public $FriendId;
    }

    class LbaNet_RemoveFriendPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::RemoveFriend', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::RemoveFriend', $facet);
        }
    }

    $LbaNet__t_RemoveFriend = IcePHP_defineClass('::LbaNet::RemoveFriend', 'LbaNet_RemoveFriend', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('FriendId', $IcePHP__t_long)));

    $LbaNet__t_RemoveFriendPrx = IcePHP_defineProxy($LbaNet__t_RemoveFriend);
}

if(!class_exists('LbaNet_RefreshFriends'))
{
    class LbaNet_RefreshFriends extends LbaNet_GuiUpdateBase
    {
        public function __construct()
        {
            parent::__construct();
        }

        public static function ice_staticId()
        {
            return '::LbaNet::RefreshFriends';
        }

        public function __toString()
        {
            global $LbaNet__t_RefreshFriends;
            return IcePHP_stringify($this, $LbaNet__t_RefreshFriends);
        }
    }

    class LbaNet_RefreshFriendsPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::RefreshFriends', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::RefreshFriends', $facet);
        }
    }

    $LbaNet__t_RefreshFriends = IcePHP_defineClass('::LbaNet::RefreshFriends', 'LbaNet_RefreshFriends', false, $LbaNet__t_GuiUpdateBase, null, null);

    $LbaNet__t_RefreshFriendsPrx = IcePHP_defineProxy($LbaNet__t_RefreshFriends);
}

if(!class_exists('LbaNet_FriendChangedUpdate'))
{
    class LbaNet_FriendChangedUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($NewInfo=null)
        {
            parent::__construct();
            $this->NewInfo = is_null($NewInfo) ? new LbaNet_FriendInfo : $NewInfo;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::FriendChangedUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_FriendChangedUpdate;
            return IcePHP_stringify($this, $LbaNet__t_FriendChangedUpdate);
        }

        public $NewInfo;
    }

    class LbaNet_FriendChangedUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::FriendChangedUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::FriendChangedUpdate', $facet);
        }
    }

    $LbaNet__t_FriendChangedUpdate = IcePHP_defineClass('::LbaNet::FriendChangedUpdate', 'LbaNet_FriendChangedUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('NewInfo', $LbaNet__t_FriendInfo)));

    $LbaNet__t_FriendChangedUpdatePrx = IcePHP_defineProxy($LbaNet__t_FriendChangedUpdate);
}

if(!class_exists('LbaNet_UpdateInventorySize'))
{
    class LbaNet_UpdateInventorySize extends LbaNet_GuiUpdateBase
    {
        public function __construct($NewSize=0)
        {
            parent::__construct();
            $this->NewSize = $NewSize;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UpdateInventorySize';
        }

        public function __toString()
        {
            global $LbaNet__t_UpdateInventorySize;
            return IcePHP_stringify($this, $LbaNet__t_UpdateInventorySize);
        }

        public $NewSize;
    }

    class LbaNet_UpdateInventorySizePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UpdateInventorySize', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UpdateInventorySize', $facet);
        }
    }

    $LbaNet__t_UpdateInventorySize = IcePHP_defineClass('::LbaNet::UpdateInventorySize', 'LbaNet_UpdateInventorySize', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('NewSize', $IcePHP__t_int)));

    $LbaNet__t_UpdateInventorySizePrx = IcePHP_defineProxy($LbaNet__t_UpdateInventorySize);
}

if(!class_exists('LbaNet_UpdateInventoryItem'))
{
    class LbaNet_UpdateInventoryItem extends LbaNet_GuiUpdateBase
    {
        public function __construct($Info=null)
        {
            parent::__construct();
            $this->Info = is_null($Info) ? new LbaNet_ItemInfo : $Info;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UpdateInventoryItem';
        }

        public function __toString()
        {
            global $LbaNet__t_UpdateInventoryItem;
            return IcePHP_stringify($this, $LbaNet__t_UpdateInventoryItem);
        }

        public $Info;
    }

    class LbaNet_UpdateInventoryItemPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UpdateInventoryItem', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UpdateInventoryItem', $facet);
        }
    }

    $LbaNet__t_UpdateInventoryItem = IcePHP_defineClass('::LbaNet::UpdateInventoryItem', 'LbaNet_UpdateInventoryItem', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Info', $LbaNet__t_ItemInfo)));

    $LbaNet__t_UpdateInventoryItemPrx = IcePHP_defineProxy($LbaNet__t_UpdateInventoryItem);
}

if(!class_exists('LbaNet_SwitchItemPosition'))
{
    class LbaNet_SwitchItemPosition extends LbaNet_GuiUpdateBase
    {
        public function __construct($ItemId=0, $NewPosition=0)
        {
            parent::__construct();
            $this->ItemId = $ItemId;
            $this->NewPosition = $NewPosition;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::SwitchItemPosition';
        }

        public function __toString()
        {
            global $LbaNet__t_SwitchItemPosition;
            return IcePHP_stringify($this, $LbaNet__t_SwitchItemPosition);
        }

        public $ItemId;
        public $NewPosition;
    }

    class LbaNet_SwitchItemPositionPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::SwitchItemPosition', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::SwitchItemPosition', $facet);
        }
    }

    $LbaNet__t_SwitchItemPosition = IcePHP_defineClass('::LbaNet::SwitchItemPosition', 'LbaNet_SwitchItemPosition', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('ItemId', $IcePHP__t_long),
    
        array('NewPosition', $IcePHP__t_int)));

    $LbaNet__t_SwitchItemPositionPrx = IcePHP_defineProxy($LbaNet__t_SwitchItemPosition);
}

if(!class_exists('LbaNet_InventoryItemUsed'))
{
    class LbaNet_InventoryItemUsed extends LbaNet_GuiUpdateBase
    {
        public function __construct($ItemId=0)
        {
            parent::__construct();
            $this->ItemId = $ItemId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::InventoryItemUsed';
        }

        public function __toString()
        {
            global $LbaNet__t_InventoryItemUsed;
            return IcePHP_stringify($this, $LbaNet__t_InventoryItemUsed);
        }

        public $ItemId;
    }

    class LbaNet_InventoryItemUsedPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::InventoryItemUsed', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::InventoryItemUsed', $facet);
        }
    }

    $LbaNet__t_InventoryItemUsed = IcePHP_defineClass('::LbaNet::InventoryItemUsed', 'LbaNet_InventoryItemUsed', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('ItemId', $IcePHP__t_long)));

    $LbaNet__t_InventoryItemUsedPrx = IcePHP_defineProxy($LbaNet__t_InventoryItemUsed);
}

if(!class_exists('LbaNet_PlayerStatusChanged'))
{
    class LbaNet_PlayerStatusChanged extends LbaNet_GuiUpdateBase
    {
        public function __construct($NewInfo=null)
        {
            parent::__construct();
            $this->NewInfo = is_null($NewInfo) ? new LbaNet_PlayerOnline : $NewInfo;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::PlayerStatusChanged';
        }

        public function __toString()
        {
            global $LbaNet__t_PlayerStatusChanged;
            return IcePHP_stringify($this, $LbaNet__t_PlayerStatusChanged);
        }

        public $NewInfo;
    }

    class LbaNet_PlayerStatusChangedPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::PlayerStatusChanged', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::PlayerStatusChanged', $facet);
        }
    }

    $LbaNet__t_PlayerStatusChanged = IcePHP_defineClass('::LbaNet::PlayerStatusChanged', 'LbaNet_PlayerStatusChanged', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('NewInfo', $LbaNet__t_PlayerOnline)));

    $LbaNet__t_PlayerStatusChangedPrx = IcePHP_defineProxy($LbaNet__t_PlayerStatusChanged);
}

if(!class_exists('LbaNet_DisplayGameText'))
{
    class LbaNet_DisplayGameText extends LbaNet_GuiUpdateBase
    {
        public function __construct($Textid=0, $Show=false)
        {
            parent::__construct();
            $this->Textid = $Textid;
            $this->Show = $Show;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::DisplayGameText';
        }

        public function __toString()
        {
            global $LbaNet__t_DisplayGameText;
            return IcePHP_stringify($this, $LbaNet__t_DisplayGameText);
        }

        public $Textid;
        public $Show;
    }

    class LbaNet_DisplayGameTextPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::DisplayGameText', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::DisplayGameText', $facet);
        }
    }

    $LbaNet__t_DisplayGameText = IcePHP_defineClass('::LbaNet::DisplayGameText', 'LbaNet_DisplayGameText', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Textid', $IcePHP__t_long),
    
        array('Show', $IcePHP__t_bool)));

    $LbaNet__t_DisplayGameTextPrx = IcePHP_defineProxy($LbaNet__t_DisplayGameText);
}

if(!class_exists('LbaNet_UpdateInvContainer'))
{
    class LbaNet_UpdateInvContainer extends LbaNet_GuiUpdateBase
    {
        public function __construct($Containerid=0, $Taken=null, $Put=null)
        {
            parent::__construct();
            $this->Containerid = $Containerid;
            $this->Taken = $Taken;
            $this->Put = $Put;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UpdateInvContainer';
        }

        public function __toString()
        {
            global $LbaNet__t_UpdateInvContainer;
            return IcePHP_stringify($this, $LbaNet__t_UpdateInvContainer);
        }

        public $Containerid;
        public $Taken;
        public $Put;
    }

    class LbaNet_UpdateInvContainerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UpdateInvContainer', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UpdateInvContainer', $facet);
        }
    }

    $LbaNet__t_UpdateInvContainer = IcePHP_defineClass('::LbaNet::UpdateInvContainer', 'LbaNet_UpdateInvContainer', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Containerid', $IcePHP__t_long),
    
        array('Taken', $LbaNet__t_ItemList),
    
        array('Put', $LbaNet__t_ItemList)));

    $LbaNet__t_UpdateInvContainerPrx = IcePHP_defineProxy($LbaNet__t_UpdateInvContainer);
}

if(!class_exists('LbaNet_SystemMessageUpdate'))
{
    class LbaNet_SystemMessageUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($Title='', $Message='')
        {
            parent::__construct();
            $this->Title = $Title;
            $this->Message = $Message;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::SystemMessageUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_SystemMessageUpdate;
            return IcePHP_stringify($this, $LbaNet__t_SystemMessageUpdate);
        }

        public $Title;
        public $Message;
    }

    class LbaNet_SystemMessageUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::SystemMessageUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::SystemMessageUpdate', $facet);
        }
    }

    $LbaNet__t_SystemMessageUpdate = IcePHP_defineClass('::LbaNet::SystemMessageUpdate', 'LbaNet_SystemMessageUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Title', $IcePHP__t_string),
    
        array('Message', $IcePHP__t_string)));

    $LbaNet__t_SystemMessageUpdatePrx = IcePHP_defineProxy($LbaNet__t_SystemMessageUpdate);
}

if(!class_exists('LbaNet_ShortcutUpdate'))
{
    class LbaNet_ShortcutUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($Position=0, $ItemId=0)
        {
            parent::__construct();
            $this->Position = $Position;
            $this->ItemId = $ItemId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ShortcutUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_ShortcutUpdate;
            return IcePHP_stringify($this, $LbaNet__t_ShortcutUpdate);
        }

        public $Position;
        public $ItemId;
    }

    class LbaNet_ShortcutUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ShortcutUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ShortcutUpdate', $facet);
        }
    }

    $LbaNet__t_ShortcutUpdate = IcePHP_defineClass('::LbaNet::ShortcutUpdate', 'LbaNet_ShortcutUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Position', $IcePHP__t_int),
    
        array('ItemId', $IcePHP__t_long)));

    $LbaNet__t_ShortcutUpdatePrx = IcePHP_defineProxy($LbaNet__t_ShortcutUpdate);
}

if(!class_exists('LbaNet_DestroyItemUpdate'))
{
    class LbaNet_DestroyItemUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($ItemId=0)
        {
            parent::__construct();
            $this->ItemId = $ItemId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::DestroyItemUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_DestroyItemUpdate;
            return IcePHP_stringify($this, $LbaNet__t_DestroyItemUpdate);
        }

        public $ItemId;
    }

    class LbaNet_DestroyItemUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::DestroyItemUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::DestroyItemUpdate', $facet);
        }
    }

    $LbaNet__t_DestroyItemUpdate = IcePHP_defineClass('::LbaNet::DestroyItemUpdate', 'LbaNet_DestroyItemUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('ItemId', $IcePHP__t_long)));

    $LbaNet__t_DestroyItemUpdatePrx = IcePHP_defineProxy($LbaNet__t_DestroyItemUpdate);
}

if(!class_exists('LbaNet_CreateLetterUpdate'))
{
    class LbaNet_CreateLetterUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($Subject='', $Message='')
        {
            parent::__construct();
            $this->Subject = $Subject;
            $this->Message = $Message;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::CreateLetterUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_CreateLetterUpdate;
            return IcePHP_stringify($this, $LbaNet__t_CreateLetterUpdate);
        }

        public $Subject;
        public $Message;
    }

    class LbaNet_CreateLetterUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::CreateLetterUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::CreateLetterUpdate', $facet);
        }
    }

    $LbaNet__t_CreateLetterUpdate = IcePHP_defineClass('::LbaNet::CreateLetterUpdate', 'LbaNet_CreateLetterUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Subject', $IcePHP__t_string),
    
        array('Message', $IcePHP__t_string)));

    $LbaNet__t_CreateLetterUpdatePrx = IcePHP_defineProxy($LbaNet__t_CreateLetterUpdate);
}

if(!class_exists('LbaNet_SendPMUpdate'))
{
    class LbaNet_SendPMUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($PM=null)
        {
            parent::__construct();
            $this->PM = is_null($PM) ? new LbaNet_PMInfo : $PM;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::SendPMUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_SendPMUpdate;
            return IcePHP_stringify($this, $LbaNet__t_SendPMUpdate);
        }

        public $PM;
    }

    class LbaNet_SendPMUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::SendPMUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::SendPMUpdate', $facet);
        }
    }

    $LbaNet__t_SendPMUpdate = IcePHP_defineClass('::LbaNet::SendPMUpdate', 'LbaNet_SendPMUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('PM', $LbaNet__t_PMInfo)));

    $LbaNet__t_SendPMUpdatePrx = IcePHP_defineProxy($LbaNet__t_SendPMUpdate);
}

if(!class_exists('LbaNet_DeletePMUpdate'))
{
    class LbaNet_DeletePMUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($PMid=0)
        {
            parent::__construct();
            $this->PMid = $PMid;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::DeletePMUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_DeletePMUpdate;
            return IcePHP_stringify($this, $LbaNet__t_DeletePMUpdate);
        }

        public $PMid;
    }

    class LbaNet_DeletePMUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::DeletePMUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::DeletePMUpdate', $facet);
        }
    }

    $LbaNet__t_DeletePMUpdate = IcePHP_defineClass('::LbaNet::DeletePMUpdate', 'LbaNet_DeletePMUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('PMid', $IcePHP__t_long)));

    $LbaNet__t_DeletePMUpdatePrx = IcePHP_defineProxy($LbaNet__t_DeletePMUpdate);
}

if(!class_exists('LbaNet_MarkReadPMUpdate'))
{
    class LbaNet_MarkReadPMUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($PMid=0)
        {
            parent::__construct();
            $this->PMid = $PMid;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::MarkReadPMUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_MarkReadPMUpdate;
            return IcePHP_stringify($this, $LbaNet__t_MarkReadPMUpdate);
        }

        public $PMid;
    }

    class LbaNet_MarkReadPMUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::MarkReadPMUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::MarkReadPMUpdate', $facet);
        }
    }

    $LbaNet__t_MarkReadPMUpdate = IcePHP_defineClass('::LbaNet::MarkReadPMUpdate', 'LbaNet_MarkReadPMUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('PMid', $IcePHP__t_long)));

    $LbaNet__t_MarkReadPMUpdatePrx = IcePHP_defineProxy($LbaNet__t_MarkReadPMUpdate);
}

if(!class_exists('LbaNet_QuestUpdate'))
{
    class LbaNet_QuestUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($Quest=null, $Finished=false)
        {
            parent::__construct();
            $this->Quest = is_null($Quest) ? new LbaNet_QuestInfo : $Quest;
            $this->Finished = $Finished;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::QuestUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_QuestUpdate;
            return IcePHP_stringify($this, $LbaNet__t_QuestUpdate);
        }

        public $Quest;
        public $Finished;
    }

    class LbaNet_QuestUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::QuestUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::QuestUpdate', $facet);
        }
    }

    $LbaNet__t_QuestUpdate = IcePHP_defineClass('::LbaNet::QuestUpdate', 'LbaNet_QuestUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Quest', $LbaNet__t_QuestInfo),
    
        array('Finished', $IcePHP__t_bool)));

    $LbaNet__t_QuestUpdatePrx = IcePHP_defineProxy($LbaNet__t_QuestUpdate);
}

if(!class_exists('LbaNet_DialogSelectedUpdate'))
{
    class LbaNet_DialogSelectedUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($NPCId=0, $SelectedId=0)
        {
            parent::__construct();
            $this->NPCId = $NPCId;
            $this->SelectedId = $SelectedId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::DialogSelectedUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_DialogSelectedUpdate;
            return IcePHP_stringify($this, $LbaNet__t_DialogSelectedUpdate);
        }

        public $NPCId;
        public $SelectedId;
    }

    class LbaNet_DialogSelectedUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::DialogSelectedUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::DialogSelectedUpdate', $facet);
        }
    }

    $LbaNet__t_DialogSelectedUpdate = IcePHP_defineClass('::LbaNet::DialogSelectedUpdate', 'LbaNet_DialogSelectedUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('NPCId', $IcePHP__t_long),
    
        array('SelectedId', $IcePHP__t_int)));

    $LbaNet__t_DialogSelectedUpdatePrx = IcePHP_defineProxy($LbaNet__t_DialogSelectedUpdate);
}

if(!class_exists('LbaNet_DialogUpdate'))
{
    class LbaNet_DialogUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($NPCId=0, $DialogPartUpdate=null)
        {
            parent::__construct();
            $this->NPCId = $NPCId;
            $this->DialogPartUpdate = is_null($DialogPartUpdate) ? new LbaNet_DialogPartInfo : $DialogPartUpdate;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::DialogUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_DialogUpdate;
            return IcePHP_stringify($this, $LbaNet__t_DialogUpdate);
        }

        public $NPCId;
        public $DialogPartUpdate;
    }

    class LbaNet_DialogUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::DialogUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::DialogUpdate', $facet);
        }
    }

    $LbaNet__t_DialogUpdate = IcePHP_defineClass('::LbaNet::DialogUpdate', 'LbaNet_DialogUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('NPCId', $IcePHP__t_long),
    
        array('DialogPartUpdate', $LbaNet__t_DialogPartInfo)));

    $LbaNet__t_DialogUpdatePrx = IcePHP_defineProxy($LbaNet__t_DialogUpdate);
}

if(!class_exists('LbaNet_GuiClosedUpdate'))
{
    class LbaNet_GuiClosedUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct()
        {
            parent::__construct();
        }

        public static function ice_staticId()
        {
            return '::LbaNet::GuiClosedUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_GuiClosedUpdate;
            return IcePHP_stringify($this, $LbaNet__t_GuiClosedUpdate);
        }
    }

    class LbaNet_GuiClosedUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::GuiClosedUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::GuiClosedUpdate', $facet);
        }
    }

    $LbaNet__t_GuiClosedUpdate = IcePHP_defineClass('::LbaNet::GuiClosedUpdate', 'LbaNet_GuiClosedUpdate', false, $LbaNet__t_GuiUpdateBase, null, null);

    $LbaNet__t_GuiClosedUpdatePrx = IcePHP_defineProxy($LbaNet__t_GuiClosedUpdate);
}

if(!class_exists('LbaNet_PlayerMoneyUpdate'))
{
    class LbaNet_PlayerMoneyUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($Quantity=0)
        {
            parent::__construct();
            $this->Quantity = $Quantity;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::PlayerMoneyUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_PlayerMoneyUpdate;
            return IcePHP_stringify($this, $LbaNet__t_PlayerMoneyUpdate);
        }

        public $Quantity;
    }

    class LbaNet_PlayerMoneyUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::PlayerMoneyUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::PlayerMoneyUpdate', $facet);
        }
    }

    $LbaNet__t_PlayerMoneyUpdate = IcePHP_defineClass('::LbaNet::PlayerMoneyUpdate', 'LbaNet_PlayerMoneyUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Quantity', $IcePHP__t_int)));

    $LbaNet__t_PlayerMoneyUpdatePrx = IcePHP_defineProxy($LbaNet__t_PlayerMoneyUpdate);
}

if(!class_exists('LbaNet_BuyItemUpdate'))
{
    class LbaNet_BuyItemUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($NPCId=0, $ItemId=0)
        {
            parent::__construct();
            $this->NPCId = $NPCId;
            $this->ItemId = $ItemId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::BuyItemUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_BuyItemUpdate;
            return IcePHP_stringify($this, $LbaNet__t_BuyItemUpdate);
        }

        public $NPCId;
        public $ItemId;
    }

    class LbaNet_BuyItemUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::BuyItemUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::BuyItemUpdate', $facet);
        }
    }

    $LbaNet__t_BuyItemUpdate = IcePHP_defineClass('::LbaNet::BuyItemUpdate', 'LbaNet_BuyItemUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('NPCId', $IcePHP__t_long),
    
        array('ItemId', $IcePHP__t_long)));

    $LbaNet__t_BuyItemUpdatePrx = IcePHP_defineProxy($LbaNet__t_BuyItemUpdate);
}

if(!class_exists('LbaNet_ChatTextUpdate'))
{
    class LbaNet_ChatTextUpdate extends LbaNet_GuiUpdateBase
    {
        public function __construct($Channel='', $Sender='', $Text='')
        {
            parent::__construct();
            $this->Channel = $Channel;
            $this->Sender = $Sender;
            $this->Text = $Text;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ChatTextUpdate';
        }

        public function __toString()
        {
            global $LbaNet__t_ChatTextUpdate;
            return IcePHP_stringify($this, $LbaNet__t_ChatTextUpdate);
        }

        public $Channel;
        public $Sender;
        public $Text;
    }

    class LbaNet_ChatTextUpdatePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ChatTextUpdate', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ChatTextUpdate', $facet);
        }
    }

    $LbaNet__t_ChatTextUpdate = IcePHP_defineClass('::LbaNet::ChatTextUpdate', 'LbaNet_ChatTextUpdate', false, $LbaNet__t_GuiUpdateBase, null, array(
        array('Channel', $IcePHP__t_string),
    
        array('Sender', $IcePHP__t_string),
    
        array('Text', $IcePHP__t_string)));

    $LbaNet__t_ChatTextUpdatePrx = IcePHP_defineProxy($LbaNet__t_ChatTextUpdate);
}

if(!class_exists('LbaNet_ClientServerEventBase'))
{
    class LbaNet_ClientServerEventBase extends Ice_ObjectImpl
    {
        public function __construct($Time=0.0)
        {
            $this->Time = $Time;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ClientServerEventBase';
        }

        public function __toString()
        {
            global $LbaNet__t_ClientServerEventBase;
            return IcePHP_stringify($this, $LbaNet__t_ClientServerEventBase);
        }

        public $Time;
    }

    class LbaNet_ClientServerEventBasePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ClientServerEventBase', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ClientServerEventBase', $facet);
        }
    }

    $LbaNet__t_ClientServerEventBase = IcePHP_defineClass('::LbaNet::ClientServerEventBase', 'LbaNet_ClientServerEventBase', false, $Ice__t_Object, null, array(
        array('Time', $IcePHP__t_double)));

    $LbaNet__t_ClientServerEventBasePrx = IcePHP_defineProxy($LbaNet__t_ClientServerEventBase);
}

if(!isset($LbaNet__t_EventsSeq))
{
    $LbaNet__t_EventsSeq = IcePHP_defineSequence('::LbaNet::EventsSeq', $LbaNet__t_ClientServerEventBase);
}

if(!class_exists('LbaNet_AvailableWorldsEvent'))
{
    class LbaNet_AvailableWorldsEvent extends LbaNet_ClientServerEventBase
    {
        public function __construct($Time=0.0, $Worlds=null)
        {
            parent::__construct($Time);
            $this->Worlds = $Worlds;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::AvailableWorldsEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_AvailableWorldsEvent;
            return IcePHP_stringify($this, $LbaNet__t_AvailableWorldsEvent);
        }

        public $Worlds;
    }

    class LbaNet_AvailableWorldsEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::AvailableWorldsEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::AvailableWorldsEvent', $facet);
        }
    }

    $LbaNet__t_AvailableWorldsEvent = IcePHP_defineClass('::LbaNet::AvailableWorldsEvent', 'LbaNet_AvailableWorldsEvent', false, $LbaNet__t_ClientServerEventBase, null, array(
        array('Worlds', $LbaNet__t_WorldsSeq)));

    $LbaNet__t_AvailableWorldsEventPrx = IcePHP_defineProxy($LbaNet__t_AvailableWorldsEvent);
}

if(!class_exists('LbaNet_RefreshGameGUIEvent'))
{
    class LbaNet_RefreshGameGUIEvent extends LbaNet_ClientServerEventBase
    {
        public function __construct($Time=0.0, $GUIId='', $Parameters=null, $Show=false, $Hide=false)
        {
            parent::__construct($Time);
            $this->GUIId = $GUIId;
            $this->Parameters = $Parameters;
            $this->Show = $Show;
            $this->Hide = $Hide;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::RefreshGameGUIEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_RefreshGameGUIEvent;
            return IcePHP_stringify($this, $LbaNet__t_RefreshGameGUIEvent);
        }

        public $GUIId;
        public $Parameters;
        public $Show;
        public $Hide;
    }

    class LbaNet_RefreshGameGUIEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::RefreshGameGUIEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::RefreshGameGUIEvent', $facet);
        }
    }

    $LbaNet__t_RefreshGameGUIEvent = IcePHP_declareClass('::LbaNet::RefreshGameGUIEvent');

    $LbaNet__t_RefreshGameGUIEvent = IcePHP_defineClass('::LbaNet::RefreshGameGUIEvent', 'LbaNet_RefreshGameGUIEvent', false, $LbaNet__t_ClientServerEventBase, null, array(
        array('GUIId', $IcePHP__t_string),
    
        array('Parameters', $LbaNet__t_GuiParamsSeq),
    
        array('Show', $IcePHP__t_bool),
    
        array('Hide', $IcePHP__t_bool)));

    $LbaNet__t_RefreshGameGUIEventPrx = IcePHP_defineProxy($LbaNet__t_RefreshGameGUIEvent);
}

if(!class_exists('LbaNet_UpdateGameGUIEvent'))
{
    class LbaNet_UpdateGameGUIEvent extends LbaNet_ClientServerEventBase
    {
        public function __construct($Time=0.0, $GUIId='', $Updates=null)
        {
            parent::__construct($Time);
            $this->GUIId = $GUIId;
            $this->Updates = $Updates;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UpdateGameGUIEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_UpdateGameGUIEvent;
            return IcePHP_stringify($this, $LbaNet__t_UpdateGameGUIEvent);
        }

        public $GUIId;
        public $Updates;
    }

    class LbaNet_UpdateGameGUIEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UpdateGameGUIEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UpdateGameGUIEvent', $facet);
        }
    }

    $LbaNet__t_UpdateGameGUIEvent = IcePHP_declareClass('::LbaNet::UpdateGameGUIEvent');

    $LbaNet__t_UpdateGameGUIEvent = IcePHP_defineClass('::LbaNet::UpdateGameGUIEvent', 'LbaNet_UpdateGameGUIEvent', false, $LbaNet__t_ClientServerEventBase, null, array(
        array('GUIId', $IcePHP__t_string),
    
        array('Updates', $LbaNet__t_GuiUpdatesSeq)));

    $LbaNet__t_UpdateGameGUIEventPrx = IcePHP_defineProxy($LbaNet__t_UpdateGameGUIEvent);
}

if(!class_exists('LbaNet_TeleportEvent'))
{
    class LbaNet_TeleportEvent extends LbaNet_ClientServerEventBase
    {
        public function __construct($Time=0.0, $TeleportId='')
        {
            parent::__construct($Time);
            $this->TeleportId = $TeleportId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::TeleportEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_TeleportEvent;
            return IcePHP_stringify($this, $LbaNet__t_TeleportEvent);
        }

        public $TeleportId;
    }

    class LbaNet_TeleportEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::TeleportEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::TeleportEvent', $facet);
        }
    }

    $LbaNet__t_TeleportEvent = IcePHP_defineClass('::LbaNet::TeleportEvent', 'LbaNet_TeleportEvent', false, $LbaNet__t_ClientServerEventBase, null, array(
        array('TeleportId', $IcePHP__t_string)));

    $LbaNet__t_TeleportEventPrx = IcePHP_defineProxy($LbaNet__t_TeleportEvent);
}

if(!class_exists('LbaNet_ChangeStanceEvent'))
{
    class LbaNet_ChangeStanceEvent extends LbaNet_ClientServerEventBase
    {
        public function __construct($Time=0.0, $NewStanceId=0)
        {
            parent::__construct($Time);
            $this->NewStanceId = $NewStanceId;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ChangeStanceEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_ChangeStanceEvent;
            return IcePHP_stringify($this, $LbaNet__t_ChangeStanceEvent);
        }

        public $NewStanceId;
    }

    class LbaNet_ChangeStanceEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ChangeStanceEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ChangeStanceEvent', $facet);
        }
    }

    $LbaNet__t_ChangeStanceEvent = IcePHP_defineClass('::LbaNet::ChangeStanceEvent', 'LbaNet_ChangeStanceEvent', false, $LbaNet__t_ClientServerEventBase, null, array(
        array('NewStanceId', $IcePHP__t_int)));

    $LbaNet__t_ChangeStanceEventPrx = IcePHP_defineProxy($LbaNet__t_ChangeStanceEvent);
}

if(!interface_exists('LbaNet_ClientInterface'))
{
    interface LbaNet_ClientInterface
    {
        public function ServerEvents($evts);
    }

    class LbaNet_ClientInterfacePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ClientInterface', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ClientInterface', $facet);
        }
    }

    $LbaNet__t_ClientInterface = IcePHP_defineClass('::LbaNet::ClientInterface', 'LbaNet_ClientInterface', true, $Ice__t_Object, null, null);

    $LbaNet__t_ClientInterfacePrx = IcePHP_defineProxy($LbaNet__t_ClientInterface);

    IcePHP_defineOperation($LbaNet__t_ClientInterface, 'ServerEvents', 0, 0, array($LbaNet__t_EventsSeq), null, null, null);
}
?>
