<?php
// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

// <auto-generated>
//
// Generated from file `PollingChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


if(!class_exists('LbaNet_ChatUserStatus'))
{
    class LbaNet_ChatUserStatus extends Ice_ObjectImpl
    {
        public function __construct($name='', $color='', $status='')
        {
            $this->name = $name;
            $this->color = $color;
            $this->status = $status;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ChatUserStatus';
        }

        public function __toString()
        {
            global $LbaNet__t_ChatUserStatus;
            return IcePHP_stringify($this, $LbaNet__t_ChatUserStatus);
        }

        public $name;
        public $color;
        public $status;
    }

    class LbaNet_ChatUserStatusPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ChatUserStatus', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ChatUserStatus', $facet);
        }
    }

    $LbaNet__t_ChatUserStatus = IcePHP_defineClass('::LbaNet::ChatUserStatus', 'LbaNet_ChatUserStatus', false, $Ice__t_Object, null, array(
        array('name', $IcePHP__t_string),
    
        array('color', $IcePHP__t_string),
    
        array('status', $IcePHP__t_string)));

    $LbaNet__t_ChatUserStatusPrx = IcePHP_defineProxy($LbaNet__t_ChatUserStatus);
}

if(!isset($LbaNet__t_UserSeq))
{
    $LbaNet__t_UserSeq = IcePHP_defineSequence('::LbaNet::UserSeq', $LbaNet__t_ChatUserStatus);
}

if(!class_exists('LbaNet_ChatRoomEvent'))
{
    class LbaNet_ChatRoomEvent extends Ice_ObjectImpl
    {
        public function __construct($timestamp=0, $name='')
        {
            $this->timestamp = $timestamp;
            $this->name = $name;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::ChatRoomEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_ChatRoomEvent;
            return IcePHP_stringify($this, $LbaNet__t_ChatRoomEvent);
        }

        public $timestamp;
        public $name;
    }

    class LbaNet_ChatRoomEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::ChatRoomEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::ChatRoomEvent', $facet);
        }
    }

    $LbaNet__t_ChatRoomEvent = IcePHP_defineClass('::LbaNet::ChatRoomEvent', 'LbaNet_ChatRoomEvent', false, $Ice__t_Object, null, array(
        array('timestamp', $IcePHP__t_long),
    
        array('name', $IcePHP__t_string)));

    $LbaNet__t_ChatRoomEventPrx = IcePHP_defineProxy($LbaNet__t_ChatRoomEvent);
}

if(!isset($LbaNet__t_ChatRoomEventSeq))
{
    $LbaNet__t_ChatRoomEventSeq = IcePHP_defineSequence('::LbaNet::ChatRoomEventSeq', $LbaNet__t_ChatRoomEvent);
}

if(!class_exists('LbaNet_UserJoinedEvent'))
{
    class LbaNet_UserJoinedEvent extends LbaNet_ChatRoomEvent
    {
        public function __construct($timestamp=0, $name='')
        {
            parent::__construct($timestamp, $name);
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UserJoinedEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_UserJoinedEvent;
            return IcePHP_stringify($this, $LbaNet__t_UserJoinedEvent);
        }
    }

    class LbaNet_UserJoinedEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UserJoinedEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UserJoinedEvent', $facet);
        }
    }

    $LbaNet__t_UserJoinedEvent = IcePHP_defineClass('::LbaNet::UserJoinedEvent', 'LbaNet_UserJoinedEvent', false, $LbaNet__t_ChatRoomEvent, null, null);

    $LbaNet__t_UserJoinedEventPrx = IcePHP_defineProxy($LbaNet__t_UserJoinedEvent);
}

if(!class_exists('LbaNet_UserLeftEvent'))
{
    class LbaNet_UserLeftEvent extends LbaNet_ChatRoomEvent
    {
        public function __construct($timestamp=0, $name='')
        {
            parent::__construct($timestamp, $name);
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UserLeftEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_UserLeftEvent;
            return IcePHP_stringify($this, $LbaNet__t_UserLeftEvent);
        }
    }

    class LbaNet_UserLeftEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UserLeftEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UserLeftEvent', $facet);
        }
    }

    $LbaNet__t_UserLeftEvent = IcePHP_defineClass('::LbaNet::UserLeftEvent', 'LbaNet_UserLeftEvent', false, $LbaNet__t_ChatRoomEvent, null, null);

    $LbaNet__t_UserLeftEventPrx = IcePHP_defineProxy($LbaNet__t_UserLeftEvent);
}

if(!class_exists('LbaNet_MessageEvent'))
{
    class LbaNet_MessageEvent extends LbaNet_ChatRoomEvent
    {
        public function __construct($timestamp=0, $name='', $message='')
        {
            parent::__construct($timestamp, $name);
            $this->message = $message;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::MessageEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_MessageEvent;
            return IcePHP_stringify($this, $LbaNet__t_MessageEvent);
        }

        public $message;
    }

    class LbaNet_MessageEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::MessageEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::MessageEvent', $facet);
        }
    }

    $LbaNet__t_MessageEvent = IcePHP_defineClass('::LbaNet::MessageEvent', 'LbaNet_MessageEvent', false, $LbaNet__t_ChatRoomEvent, null, array(
        array('message', $IcePHP__t_string)));

    $LbaNet__t_MessageEventPrx = IcePHP_defineProxy($LbaNet__t_MessageEvent);
}

if(!class_exists('LbaNet_UserStatusEvent'))
{
    class LbaNet_UserStatusEvent extends LbaNet_ChatRoomEvent
    {
        public function __construct($timestamp=0, $name='', $color='', $status='')
        {
            parent::__construct($timestamp, $name);
            $this->color = $color;
            $this->status = $status;
        }

        public static function ice_staticId()
        {
            return '::LbaNet::UserStatusEvent';
        }

        public function __toString()
        {
            global $LbaNet__t_UserStatusEvent;
            return IcePHP_stringify($this, $LbaNet__t_UserStatusEvent);
        }

        public $color;
        public $status;
    }

    class LbaNet_UserStatusEventPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::UserStatusEvent', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::UserStatusEvent', $facet);
        }
    }

    $LbaNet__t_UserStatusEvent = IcePHP_defineClass('::LbaNet::UserStatusEvent', 'LbaNet_UserStatusEvent', false, $LbaNet__t_ChatRoomEvent, null, array(
        array('color', $IcePHP__t_string),
    
        array('status', $IcePHP__t_string)));

    $LbaNet__t_UserStatusEventPrx = IcePHP_defineProxy($LbaNet__t_UserStatusEvent);
}

if(!interface_exists('LbaNet_PollingChatSession'))
{
    interface LbaNet_PollingChatSession
    {
        public function getInitialUsers();
        public function getUpdates();
        public function send($message);
        public function destroy();
    }

    class LbaNet_PollingChatSessionPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::PollingChatSession', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::PollingChatSession', $facet);
        }
    }

    $LbaNet__t_PollingChatSession = IcePHP_defineClass('::LbaNet::PollingChatSession', 'LbaNet_PollingChatSession', true, $Ice__t_Object, null, null);

    $LbaNet__t_PollingChatSessionPrx = IcePHP_defineProxy($LbaNet__t_PollingChatSession);

    IcePHP_defineOperation($LbaNet__t_PollingChatSession, 'getInitialUsers', 0, 0, null, null, $LbaNet__t_UserSeq, null);
    IcePHP_defineOperation($LbaNet__t_PollingChatSession, 'getUpdates', 0, 0, null, null, $LbaNet__t_ChatRoomEventSeq, null);
    IcePHP_defineOperation($LbaNet__t_PollingChatSession, 'send', 0, 0, array($IcePHP__t_string), null, $IcePHP__t_long, null);
    IcePHP_defineOperation($LbaNet__t_PollingChatSession, 'destroy', 0, 0, null, null, null, null);
}

if(!class_exists('LbaNet_CannotCreateSessionException'))
{
    class LbaNet_CannotCreateSessionException extends Ice_UserException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'LbaNet::CannotCreateSessionException';
        }

        public function __toString()
        {
            global $LbaNet__t_CannotCreateSessionException;
            return IcePHP_stringifyException($this, $LbaNet__t_CannotCreateSessionException);
        }

        public $reason;
    }

    $LbaNet__t_CannotCreateSessionException = IcePHP_defineException('::LbaNet::CannotCreateSessionException', 'LbaNet_CannotCreateSessionException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!interface_exists('LbaNet_PollingChatSessionFactory'))
{
    interface LbaNet_PollingChatSessionFactory
    {
        public function create($name, $password);
    }

    class LbaNet_PollingChatSessionFactoryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::LbaNet::PollingChatSessionFactory', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::LbaNet::PollingChatSessionFactory', $facet);
        }
    }

    $LbaNet__t_PollingChatSessionFactory = IcePHP_defineClass('::LbaNet::PollingChatSessionFactory', 'LbaNet_PollingChatSessionFactory', true, $Ice__t_Object, null, null);

    $LbaNet__t_PollingChatSessionFactoryPrx = IcePHP_defineProxy($LbaNet__t_PollingChatSessionFactory);

    IcePHP_defineOperation($LbaNet__t_PollingChatSessionFactory, 'create', 0, 0, array($IcePHP__t_string, $IcePHP__t_string), null, $LbaNet__t_PollingChatSessionPrx, array($LbaNet__t_CannotCreateSessionException));
}
?>
