<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `CommunicatorF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!isset($Ice__t_Communicator))
{
    $Ice__t_Communicator = IcePHP_declareClass('::Ice::Communicator');
}
?>
