<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ConnectionF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!isset($Ice__t_ConnectionInfo))
{
    $Ice__t_ConnectionInfo = IcePHP_declareClass('::Ice::ConnectionInfo');
}

if(!isset($Ice__t_Connection))
{
    $Ice__t_Connection = IcePHP_declareClass('::Ice::Connection');
}
?>
