<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once 'Ice/Identity.php';
require_once 'Ice/BuiltinSequences.php';

if(!class_exists('Ice_InitializationException'))
{
    class Ice_InitializationException extends Ice_LocalException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'Ice::InitializationException';
        }

        public function __toString()
        {
            global $Ice__t_InitializationException;
            return IcePHP_stringifyException($this, $Ice__t_InitializationException);
        }

        public $reason;
    }

    $Ice__t_InitializationException = IcePHP_defineException('::Ice::InitializationException', 'Ice_InitializationException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!class_exists('Ice_PluginInitializationException'))
{
    class Ice_PluginInitializationException extends Ice_LocalException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'Ice::PluginInitializationException';
        }

        public function __toString()
        {
            global $Ice__t_PluginInitializationException;
            return IcePHP_stringifyException($this, $Ice__t_PluginInitializationException);
        }

        public $reason;
    }

    $Ice__t_PluginInitializationException = IcePHP_defineException('::Ice::PluginInitializationException', 'Ice_PluginInitializationException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!class_exists('Ice_CollocationOptimizationException'))
{
    class Ice_CollocationOptimizationException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::CollocationOptimizationException';
        }

        public function __toString()
        {
            global $Ice__t_CollocationOptimizationException;
            return IcePHP_stringifyException($this, $Ice__t_CollocationOptimizationException);
        }
    }

    $Ice__t_CollocationOptimizationException = IcePHP_defineException('::Ice::CollocationOptimizationException', 'Ice_CollocationOptimizationException', null, null);
}

if(!class_exists('Ice_AlreadyRegisteredException'))
{
    class Ice_AlreadyRegisteredException extends Ice_LocalException
    {
        public function __construct($kindOfObject='', $id='')
        {
            $this->kindOfObject = $kindOfObject;
            $this->id = $id;
        }

        public function ice_name()
        {
            return 'Ice::AlreadyRegisteredException';
        }

        public function __toString()
        {
            global $Ice__t_AlreadyRegisteredException;
            return IcePHP_stringifyException($this, $Ice__t_AlreadyRegisteredException);
        }

        public $kindOfObject;
        public $id;
    }

    $Ice__t_AlreadyRegisteredException = IcePHP_defineException('::Ice::AlreadyRegisteredException', 'Ice_AlreadyRegisteredException', null, array(
        array('kindOfObject', $IcePHP__t_string),
    
        array('id', $IcePHP__t_string)));
}

if(!class_exists('Ice_NotRegisteredException'))
{
    class Ice_NotRegisteredException extends Ice_LocalException
    {
        public function __construct($kindOfObject='', $id='')
        {
            $this->kindOfObject = $kindOfObject;
            $this->id = $id;
        }

        public function ice_name()
        {
            return 'Ice::NotRegisteredException';
        }

        public function __toString()
        {
            global $Ice__t_NotRegisteredException;
            return IcePHP_stringifyException($this, $Ice__t_NotRegisteredException);
        }

        public $kindOfObject;
        public $id;
    }

    $Ice__t_NotRegisteredException = IcePHP_defineException('::Ice::NotRegisteredException', 'Ice_NotRegisteredException', null, array(
        array('kindOfObject', $IcePHP__t_string),
    
        array('id', $IcePHP__t_string)));
}

if(!class_exists('Ice_TwowayOnlyException'))
{
    class Ice_TwowayOnlyException extends Ice_LocalException
    {
        public function __construct($operation='')
        {
            $this->operation = $operation;
        }

        public function ice_name()
        {
            return 'Ice::TwowayOnlyException';
        }

        public function __toString()
        {
            global $Ice__t_TwowayOnlyException;
            return IcePHP_stringifyException($this, $Ice__t_TwowayOnlyException);
        }

        public $operation;
    }

    $Ice__t_TwowayOnlyException = IcePHP_defineException('::Ice::TwowayOnlyException', 'Ice_TwowayOnlyException', null, array(
        array('operation', $IcePHP__t_string)));
}

if(!class_exists('Ice_CloneNotImplementedException'))
{
    class Ice_CloneNotImplementedException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::CloneNotImplementedException';
        }

        public function __toString()
        {
            global $Ice__t_CloneNotImplementedException;
            return IcePHP_stringifyException($this, $Ice__t_CloneNotImplementedException);
        }
    }

    $Ice__t_CloneNotImplementedException = IcePHP_defineException('::Ice::CloneNotImplementedException', 'Ice_CloneNotImplementedException', null, null);
}

if(!class_exists('Ice_UnknownException'))
{
    class Ice_UnknownException extends Ice_LocalException
    {
        public function __construct($unknown='')
        {
            $this->unknown = $unknown;
        }

        public function ice_name()
        {
            return 'Ice::UnknownException';
        }

        public function __toString()
        {
            global $Ice__t_UnknownException;
            return IcePHP_stringifyException($this, $Ice__t_UnknownException);
        }

        public $unknown;
    }

    $Ice__t_UnknownException = IcePHP_defineException('::Ice::UnknownException', 'Ice_UnknownException', null, array(
        array('unknown', $IcePHP__t_string)));
}

if(!class_exists('Ice_UnknownLocalException'))
{
    class Ice_UnknownLocalException extends Ice_UnknownException
    {
        public function __construct($unknown='')
        {
            parent::__construct($unknown);
        }

        public function ice_name()
        {
            return 'Ice::UnknownLocalException';
        }

        public function __toString()
        {
            global $Ice__t_UnknownLocalException;
            return IcePHP_stringifyException($this, $Ice__t_UnknownLocalException);
        }
    }

    $Ice__t_UnknownLocalException = IcePHP_defineException('::Ice::UnknownLocalException', 'Ice_UnknownLocalException', $Ice__t_UnknownException, null);
}

if(!class_exists('Ice_UnknownUserException'))
{
    class Ice_UnknownUserException extends Ice_UnknownException
    {
        public function __construct($unknown='')
        {
            parent::__construct($unknown);
        }

        public function ice_name()
        {
            return 'Ice::UnknownUserException';
        }

        public function __toString()
        {
            global $Ice__t_UnknownUserException;
            return IcePHP_stringifyException($this, $Ice__t_UnknownUserException);
        }
    }

    $Ice__t_UnknownUserException = IcePHP_defineException('::Ice::UnknownUserException', 'Ice_UnknownUserException', $Ice__t_UnknownException, null);
}

if(!class_exists('Ice_VersionMismatchException'))
{
    class Ice_VersionMismatchException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::VersionMismatchException';
        }

        public function __toString()
        {
            global $Ice__t_VersionMismatchException;
            return IcePHP_stringifyException($this, $Ice__t_VersionMismatchException);
        }
    }

    $Ice__t_VersionMismatchException = IcePHP_defineException('::Ice::VersionMismatchException', 'Ice_VersionMismatchException', null, null);
}

if(!class_exists('Ice_CommunicatorDestroyedException'))
{
    class Ice_CommunicatorDestroyedException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::CommunicatorDestroyedException';
        }

        public function __toString()
        {
            global $Ice__t_CommunicatorDestroyedException;
            return IcePHP_stringifyException($this, $Ice__t_CommunicatorDestroyedException);
        }
    }

    $Ice__t_CommunicatorDestroyedException = IcePHP_defineException('::Ice::CommunicatorDestroyedException', 'Ice_CommunicatorDestroyedException', null, null);
}

if(!class_exists('Ice_ObjectAdapterDeactivatedException'))
{
    class Ice_ObjectAdapterDeactivatedException extends Ice_LocalException
    {
        public function __construct($name='')
        {
            $this->name = $name;
        }

        public function ice_name()
        {
            return 'Ice::ObjectAdapterDeactivatedException';
        }

        public function __toString()
        {
            global $Ice__t_ObjectAdapterDeactivatedException;
            return IcePHP_stringifyException($this, $Ice__t_ObjectAdapterDeactivatedException);
        }

        public $name;
    }

    $Ice__t_ObjectAdapterDeactivatedException = IcePHP_defineException('::Ice::ObjectAdapterDeactivatedException', 'Ice_ObjectAdapterDeactivatedException', null, array(
        array('name', $IcePHP__t_string)));
}

if(!class_exists('Ice_ObjectAdapterIdInUseException'))
{
    class Ice_ObjectAdapterIdInUseException extends Ice_LocalException
    {
        public function __construct($id='')
        {
            $this->id = $id;
        }

        public function ice_name()
        {
            return 'Ice::ObjectAdapterIdInUseException';
        }

        public function __toString()
        {
            global $Ice__t_ObjectAdapterIdInUseException;
            return IcePHP_stringifyException($this, $Ice__t_ObjectAdapterIdInUseException);
        }

        public $id;
    }

    $Ice__t_ObjectAdapterIdInUseException = IcePHP_defineException('::Ice::ObjectAdapterIdInUseException', 'Ice_ObjectAdapterIdInUseException', null, array(
        array('id', $IcePHP__t_string)));
}

if(!class_exists('Ice_NoEndpointException'))
{
    class Ice_NoEndpointException extends Ice_LocalException
    {
        public function __construct($proxy='')
        {
            $this->proxy = $proxy;
        }

        public function ice_name()
        {
            return 'Ice::NoEndpointException';
        }

        public function __toString()
        {
            global $Ice__t_NoEndpointException;
            return IcePHP_stringifyException($this, $Ice__t_NoEndpointException);
        }

        public $proxy;
    }

    $Ice__t_NoEndpointException = IcePHP_defineException('::Ice::NoEndpointException', 'Ice_NoEndpointException', null, array(
        array('proxy', $IcePHP__t_string)));
}

if(!class_exists('Ice_EndpointParseException'))
{
    class Ice_EndpointParseException extends Ice_LocalException
    {
        public function __construct($str='')
        {
            $this->str = $str;
        }

        public function ice_name()
        {
            return 'Ice::EndpointParseException';
        }

        public function __toString()
        {
            global $Ice__t_EndpointParseException;
            return IcePHP_stringifyException($this, $Ice__t_EndpointParseException);
        }

        public $str;
    }

    $Ice__t_EndpointParseException = IcePHP_defineException('::Ice::EndpointParseException', 'Ice_EndpointParseException', null, array(
        array('str', $IcePHP__t_string)));
}

if(!class_exists('Ice_EndpointSelectionTypeParseException'))
{
    class Ice_EndpointSelectionTypeParseException extends Ice_LocalException
    {
        public function __construct($str='')
        {
            $this->str = $str;
        }

        public function ice_name()
        {
            return 'Ice::EndpointSelectionTypeParseException';
        }

        public function __toString()
        {
            global $Ice__t_EndpointSelectionTypeParseException;
            return IcePHP_stringifyException($this, $Ice__t_EndpointSelectionTypeParseException);
        }

        public $str;
    }

    $Ice__t_EndpointSelectionTypeParseException = IcePHP_defineException('::Ice::EndpointSelectionTypeParseException', 'Ice_EndpointSelectionTypeParseException', null, array(
        array('str', $IcePHP__t_string)));
}

if(!class_exists('Ice_IdentityParseException'))
{
    class Ice_IdentityParseException extends Ice_LocalException
    {
        public function __construct($str='')
        {
            $this->str = $str;
        }

        public function ice_name()
        {
            return 'Ice::IdentityParseException';
        }

        public function __toString()
        {
            global $Ice__t_IdentityParseException;
            return IcePHP_stringifyException($this, $Ice__t_IdentityParseException);
        }

        public $str;
    }

    $Ice__t_IdentityParseException = IcePHP_defineException('::Ice::IdentityParseException', 'Ice_IdentityParseException', null, array(
        array('str', $IcePHP__t_string)));
}

if(!class_exists('Ice_ProxyParseException'))
{
    class Ice_ProxyParseException extends Ice_LocalException
    {
        public function __construct($str='')
        {
            $this->str = $str;
        }

        public function ice_name()
        {
            return 'Ice::ProxyParseException';
        }

        public function __toString()
        {
            global $Ice__t_ProxyParseException;
            return IcePHP_stringifyException($this, $Ice__t_ProxyParseException);
        }

        public $str;
    }

    $Ice__t_ProxyParseException = IcePHP_defineException('::Ice::ProxyParseException', 'Ice_ProxyParseException', null, array(
        array('str', $IcePHP__t_string)));
}

if(!class_exists('Ice_IllegalIdentityException'))
{
    class Ice_IllegalIdentityException extends Ice_LocalException
    {
        public function __construct($id=null)
        {
            $this->id = is_null($id) ? new Ice_Identity : $id;
        }

        public function ice_name()
        {
            return 'Ice::IllegalIdentityException';
        }

        public function __toString()
        {
            global $Ice__t_IllegalIdentityException;
            return IcePHP_stringifyException($this, $Ice__t_IllegalIdentityException);
        }

        public $id;
    }

    $Ice__t_IllegalIdentityException = IcePHP_defineException('::Ice::IllegalIdentityException', 'Ice_IllegalIdentityException', null, array(
        array('id', $Ice__t_Identity)));
}

if(!class_exists('Ice_RequestFailedException'))
{
    class Ice_RequestFailedException extends Ice_LocalException
    {
        public function __construct($id=null, $facet='', $operation='')
        {
            $this->id = is_null($id) ? new Ice_Identity : $id;
            $this->facet = $facet;
            $this->operation = $operation;
        }

        public function ice_name()
        {
            return 'Ice::RequestFailedException';
        }

        public function __toString()
        {
            global $Ice__t_RequestFailedException;
            return IcePHP_stringifyException($this, $Ice__t_RequestFailedException);
        }

        public $id;
        public $facet;
        public $operation;
    }

    $Ice__t_RequestFailedException = IcePHP_defineException('::Ice::RequestFailedException', 'Ice_RequestFailedException', null, array(
        array('id', $Ice__t_Identity),
    
        array('facet', $IcePHP__t_string),
    
        array('operation', $IcePHP__t_string)));
}

if(!class_exists('Ice_ObjectNotExistException'))
{
    class Ice_ObjectNotExistException extends Ice_RequestFailedException
    {
        public function __construct($id=null, $facet='', $operation='')
        {
            parent::__construct($id, $facet, $operation);
        }

        public function ice_name()
        {
            return 'Ice::ObjectNotExistException';
        }

        public function __toString()
        {
            global $Ice__t_ObjectNotExistException;
            return IcePHP_stringifyException($this, $Ice__t_ObjectNotExistException);
        }
    }

    $Ice__t_ObjectNotExistException = IcePHP_defineException('::Ice::ObjectNotExistException', 'Ice_ObjectNotExistException', $Ice__t_RequestFailedException, null);
}

if(!class_exists('Ice_FacetNotExistException'))
{
    class Ice_FacetNotExistException extends Ice_RequestFailedException
    {
        public function __construct($id=null, $facet='', $operation='')
        {
            parent::__construct($id, $facet, $operation);
        }

        public function ice_name()
        {
            return 'Ice::FacetNotExistException';
        }

        public function __toString()
        {
            global $Ice__t_FacetNotExistException;
            return IcePHP_stringifyException($this, $Ice__t_FacetNotExistException);
        }
    }

    $Ice__t_FacetNotExistException = IcePHP_defineException('::Ice::FacetNotExistException', 'Ice_FacetNotExistException', $Ice__t_RequestFailedException, null);
}

if(!class_exists('Ice_OperationNotExistException'))
{
    class Ice_OperationNotExistException extends Ice_RequestFailedException
    {
        public function __construct($id=null, $facet='', $operation='')
        {
            parent::__construct($id, $facet, $operation);
        }

        public function ice_name()
        {
            return 'Ice::OperationNotExistException';
        }

        public function __toString()
        {
            global $Ice__t_OperationNotExistException;
            return IcePHP_stringifyException($this, $Ice__t_OperationNotExistException);
        }
    }

    $Ice__t_OperationNotExistException = IcePHP_defineException('::Ice::OperationNotExistException', 'Ice_OperationNotExistException', $Ice__t_RequestFailedException, null);
}

if(!class_exists('Ice_SyscallException'))
{
    class Ice_SyscallException extends Ice_LocalException
    {
        public function __construct($error=0)
        {
            $this->error = $error;
        }

        public function ice_name()
        {
            return 'Ice::SyscallException';
        }

        public function __toString()
        {
            global $Ice__t_SyscallException;
            return IcePHP_stringifyException($this, $Ice__t_SyscallException);
        }

        public $error;
    }

    $Ice__t_SyscallException = IcePHP_defineException('::Ice::SyscallException', 'Ice_SyscallException', null, array(
        array('error', $IcePHP__t_int)));
}

if(!class_exists('Ice_SocketException'))
{
    class Ice_SocketException extends Ice_SyscallException
    {
        public function __construct($error=0)
        {
            parent::__construct($error);
        }

        public function ice_name()
        {
            return 'Ice::SocketException';
        }

        public function __toString()
        {
            global $Ice__t_SocketException;
            return IcePHP_stringifyException($this, $Ice__t_SocketException);
        }
    }

    $Ice__t_SocketException = IcePHP_defineException('::Ice::SocketException', 'Ice_SocketException', $Ice__t_SyscallException, null);
}

if(!class_exists('Ice_FileException'))
{
    class Ice_FileException extends Ice_SyscallException
    {
        public function __construct($error=0, $path='')
        {
            parent::__construct($error);
            $this->path = $path;
        }

        public function ice_name()
        {
            return 'Ice::FileException';
        }

        public function __toString()
        {
            global $Ice__t_FileException;
            return IcePHP_stringifyException($this, $Ice__t_FileException);
        }

        public $path;
    }

    $Ice__t_FileException = IcePHP_defineException('::Ice::FileException', 'Ice_FileException', $Ice__t_SyscallException, array(
        array('path', $IcePHP__t_string)));
}

if(!class_exists('Ice_ConnectFailedException'))
{
    class Ice_ConnectFailedException extends Ice_SocketException
    {
        public function __construct($error=0)
        {
            parent::__construct($error);
        }

        public function ice_name()
        {
            return 'Ice::ConnectFailedException';
        }

        public function __toString()
        {
            global $Ice__t_ConnectFailedException;
            return IcePHP_stringifyException($this, $Ice__t_ConnectFailedException);
        }
    }

    $Ice__t_ConnectFailedException = IcePHP_defineException('::Ice::ConnectFailedException', 'Ice_ConnectFailedException', $Ice__t_SocketException, null);
}

if(!class_exists('Ice_ConnectionRefusedException'))
{
    class Ice_ConnectionRefusedException extends Ice_ConnectFailedException
    {
        public function __construct($error=0)
        {
            parent::__construct($error);
        }

        public function ice_name()
        {
            return 'Ice::ConnectionRefusedException';
        }

        public function __toString()
        {
            global $Ice__t_ConnectionRefusedException;
            return IcePHP_stringifyException($this, $Ice__t_ConnectionRefusedException);
        }
    }

    $Ice__t_ConnectionRefusedException = IcePHP_defineException('::Ice::ConnectionRefusedException', 'Ice_ConnectionRefusedException', $Ice__t_ConnectFailedException, null);
}

if(!class_exists('Ice_ConnectionLostException'))
{
    class Ice_ConnectionLostException extends Ice_SocketException
    {
        public function __construct($error=0)
        {
            parent::__construct($error);
        }

        public function ice_name()
        {
            return 'Ice::ConnectionLostException';
        }

        public function __toString()
        {
            global $Ice__t_ConnectionLostException;
            return IcePHP_stringifyException($this, $Ice__t_ConnectionLostException);
        }
    }

    $Ice__t_ConnectionLostException = IcePHP_defineException('::Ice::ConnectionLostException', 'Ice_ConnectionLostException', $Ice__t_SocketException, null);
}

if(!class_exists('Ice_DNSException'))
{
    class Ice_DNSException extends Ice_LocalException
    {
        public function __construct($error=0, $host='')
        {
            $this->error = $error;
            $this->host = $host;
        }

        public function ice_name()
        {
            return 'Ice::DNSException';
        }

        public function __toString()
        {
            global $Ice__t_DNSException;
            return IcePHP_stringifyException($this, $Ice__t_DNSException);
        }

        public $error;
        public $host;
    }

    $Ice__t_DNSException = IcePHP_defineException('::Ice::DNSException', 'Ice_DNSException', null, array(
        array('error', $IcePHP__t_int),
    
        array('host', $IcePHP__t_string)));
}

if(!class_exists('Ice_TimeoutException'))
{
    class Ice_TimeoutException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::TimeoutException';
        }

        public function __toString()
        {
            global $Ice__t_TimeoutException;
            return IcePHP_stringifyException($this, $Ice__t_TimeoutException);
        }
    }

    $Ice__t_TimeoutException = IcePHP_defineException('::Ice::TimeoutException', 'Ice_TimeoutException', null, null);
}

if(!class_exists('Ice_ConnectTimeoutException'))
{
    class Ice_ConnectTimeoutException extends Ice_TimeoutException
    {
        public function __construct()
        {
            parent::__construct();
        }

        public function ice_name()
        {
            return 'Ice::ConnectTimeoutException';
        }

        public function __toString()
        {
            global $Ice__t_ConnectTimeoutException;
            return IcePHP_stringifyException($this, $Ice__t_ConnectTimeoutException);
        }
    }

    $Ice__t_ConnectTimeoutException = IcePHP_defineException('::Ice::ConnectTimeoutException', 'Ice_ConnectTimeoutException', $Ice__t_TimeoutException, null);
}

if(!class_exists('Ice_CloseTimeoutException'))
{
    class Ice_CloseTimeoutException extends Ice_TimeoutException
    {
        public function __construct()
        {
            parent::__construct();
        }

        public function ice_name()
        {
            return 'Ice::CloseTimeoutException';
        }

        public function __toString()
        {
            global $Ice__t_CloseTimeoutException;
            return IcePHP_stringifyException($this, $Ice__t_CloseTimeoutException);
        }
    }

    $Ice__t_CloseTimeoutException = IcePHP_defineException('::Ice::CloseTimeoutException', 'Ice_CloseTimeoutException', $Ice__t_TimeoutException, null);
}

if(!class_exists('Ice_ConnectionTimeoutException'))
{
    class Ice_ConnectionTimeoutException extends Ice_TimeoutException
    {
        public function __construct()
        {
            parent::__construct();
        }

        public function ice_name()
        {
            return 'Ice::ConnectionTimeoutException';
        }

        public function __toString()
        {
            global $Ice__t_ConnectionTimeoutException;
            return IcePHP_stringifyException($this, $Ice__t_ConnectionTimeoutException);
        }
    }

    $Ice__t_ConnectionTimeoutException = IcePHP_defineException('::Ice::ConnectionTimeoutException', 'Ice_ConnectionTimeoutException', $Ice__t_TimeoutException, null);
}

if(!class_exists('Ice_ProtocolException'))
{
    class Ice_ProtocolException extends Ice_LocalException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'Ice::ProtocolException';
        }

        public function __toString()
        {
            global $Ice__t_ProtocolException;
            return IcePHP_stringifyException($this, $Ice__t_ProtocolException);
        }

        public $reason;
    }

    $Ice__t_ProtocolException = IcePHP_defineException('::Ice::ProtocolException', 'Ice_ProtocolException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!class_exists('Ice_BadMagicException'))
{
    class Ice_BadMagicException extends Ice_ProtocolException
    {
        public function __construct($reason='', $badMagic=null)
        {
            parent::__construct($reason);
            $this->badMagic = $badMagic;
        }

        public function ice_name()
        {
            return 'Ice::BadMagicException';
        }

        public function __toString()
        {
            global $Ice__t_BadMagicException;
            return IcePHP_stringifyException($this, $Ice__t_BadMagicException);
        }

        public $badMagic;
    }

    $Ice__t_BadMagicException = IcePHP_defineException('::Ice::BadMagicException', 'Ice_BadMagicException', $Ice__t_ProtocolException, array(
        array('badMagic', $Ice__t_ByteSeq)));
}

if(!class_exists('Ice_UnsupportedProtocolException'))
{
    class Ice_UnsupportedProtocolException extends Ice_ProtocolException
    {
        public function __construct($reason='', $badMajor=0, $badMinor=0, $major=0, $minor=0)
        {
            parent::__construct($reason);
            $this->badMajor = $badMajor;
            $this->badMinor = $badMinor;
            $this->major = $major;
            $this->minor = $minor;
        }

        public function ice_name()
        {
            return 'Ice::UnsupportedProtocolException';
        }

        public function __toString()
        {
            global $Ice__t_UnsupportedProtocolException;
            return IcePHP_stringifyException($this, $Ice__t_UnsupportedProtocolException);
        }

        public $badMajor;
        public $badMinor;
        public $major;
        public $minor;
    }

    $Ice__t_UnsupportedProtocolException = IcePHP_defineException('::Ice::UnsupportedProtocolException', 'Ice_UnsupportedProtocolException', $Ice__t_ProtocolException, array(
        array('badMajor', $IcePHP__t_int),
    
        array('badMinor', $IcePHP__t_int),
    
        array('major', $IcePHP__t_int),
    
        array('minor', $IcePHP__t_int)));
}

if(!class_exists('Ice_UnsupportedEncodingException'))
{
    class Ice_UnsupportedEncodingException extends Ice_ProtocolException
    {
        public function __construct($reason='', $badMajor=0, $badMinor=0, $major=0, $minor=0)
        {
            parent::__construct($reason);
            $this->badMajor = $badMajor;
            $this->badMinor = $badMinor;
            $this->major = $major;
            $this->minor = $minor;
        }

        public function ice_name()
        {
            return 'Ice::UnsupportedEncodingException';
        }

        public function __toString()
        {
            global $Ice__t_UnsupportedEncodingException;
            return IcePHP_stringifyException($this, $Ice__t_UnsupportedEncodingException);
        }

        public $badMajor;
        public $badMinor;
        public $major;
        public $minor;
    }

    $Ice__t_UnsupportedEncodingException = IcePHP_defineException('::Ice::UnsupportedEncodingException', 'Ice_UnsupportedEncodingException', $Ice__t_ProtocolException, array(
        array('badMajor', $IcePHP__t_int),
    
        array('badMinor', $IcePHP__t_int),
    
        array('major', $IcePHP__t_int),
    
        array('minor', $IcePHP__t_int)));
}

if(!class_exists('Ice_UnknownMessageException'))
{
    class Ice_UnknownMessageException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::UnknownMessageException';
        }

        public function __toString()
        {
            global $Ice__t_UnknownMessageException;
            return IcePHP_stringifyException($this, $Ice__t_UnknownMessageException);
        }
    }

    $Ice__t_UnknownMessageException = IcePHP_defineException('::Ice::UnknownMessageException', 'Ice_UnknownMessageException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_ConnectionNotValidatedException'))
{
    class Ice_ConnectionNotValidatedException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::ConnectionNotValidatedException';
        }

        public function __toString()
        {
            global $Ice__t_ConnectionNotValidatedException;
            return IcePHP_stringifyException($this, $Ice__t_ConnectionNotValidatedException);
        }
    }

    $Ice__t_ConnectionNotValidatedException = IcePHP_defineException('::Ice::ConnectionNotValidatedException', 'Ice_ConnectionNotValidatedException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_UnknownRequestIdException'))
{
    class Ice_UnknownRequestIdException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::UnknownRequestIdException';
        }

        public function __toString()
        {
            global $Ice__t_UnknownRequestIdException;
            return IcePHP_stringifyException($this, $Ice__t_UnknownRequestIdException);
        }
    }

    $Ice__t_UnknownRequestIdException = IcePHP_defineException('::Ice::UnknownRequestIdException', 'Ice_UnknownRequestIdException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_UnknownReplyStatusException'))
{
    class Ice_UnknownReplyStatusException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::UnknownReplyStatusException';
        }

        public function __toString()
        {
            global $Ice__t_UnknownReplyStatusException;
            return IcePHP_stringifyException($this, $Ice__t_UnknownReplyStatusException);
        }
    }

    $Ice__t_UnknownReplyStatusException = IcePHP_defineException('::Ice::UnknownReplyStatusException', 'Ice_UnknownReplyStatusException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_CloseConnectionException'))
{
    class Ice_CloseConnectionException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::CloseConnectionException';
        }

        public function __toString()
        {
            global $Ice__t_CloseConnectionException;
            return IcePHP_stringifyException($this, $Ice__t_CloseConnectionException);
        }
    }

    $Ice__t_CloseConnectionException = IcePHP_defineException('::Ice::CloseConnectionException', 'Ice_CloseConnectionException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_ForcedCloseConnectionException'))
{
    class Ice_ForcedCloseConnectionException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::ForcedCloseConnectionException';
        }

        public function __toString()
        {
            global $Ice__t_ForcedCloseConnectionException;
            return IcePHP_stringifyException($this, $Ice__t_ForcedCloseConnectionException);
        }
    }

    $Ice__t_ForcedCloseConnectionException = IcePHP_defineException('::Ice::ForcedCloseConnectionException', 'Ice_ForcedCloseConnectionException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_IllegalMessageSizeException'))
{
    class Ice_IllegalMessageSizeException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::IllegalMessageSizeException';
        }

        public function __toString()
        {
            global $Ice__t_IllegalMessageSizeException;
            return IcePHP_stringifyException($this, $Ice__t_IllegalMessageSizeException);
        }
    }

    $Ice__t_IllegalMessageSizeException = IcePHP_defineException('::Ice::IllegalMessageSizeException', 'Ice_IllegalMessageSizeException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_CompressionException'))
{
    class Ice_CompressionException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::CompressionException';
        }

        public function __toString()
        {
            global $Ice__t_CompressionException;
            return IcePHP_stringifyException($this, $Ice__t_CompressionException);
        }
    }

    $Ice__t_CompressionException = IcePHP_defineException('::Ice::CompressionException', 'Ice_CompressionException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_DatagramLimitException'))
{
    class Ice_DatagramLimitException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::DatagramLimitException';
        }

        public function __toString()
        {
            global $Ice__t_DatagramLimitException;
            return IcePHP_stringifyException($this, $Ice__t_DatagramLimitException);
        }
    }

    $Ice__t_DatagramLimitException = IcePHP_defineException('::Ice::DatagramLimitException', 'Ice_DatagramLimitException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_MarshalException'))
{
    class Ice_MarshalException extends Ice_ProtocolException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::MarshalException';
        }

        public function __toString()
        {
            global $Ice__t_MarshalException;
            return IcePHP_stringifyException($this, $Ice__t_MarshalException);
        }
    }

    $Ice__t_MarshalException = IcePHP_defineException('::Ice::MarshalException', 'Ice_MarshalException', $Ice__t_ProtocolException, null);
}

if(!class_exists('Ice_ProxyUnmarshalException'))
{
    class Ice_ProxyUnmarshalException extends Ice_MarshalException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::ProxyUnmarshalException';
        }

        public function __toString()
        {
            global $Ice__t_ProxyUnmarshalException;
            return IcePHP_stringifyException($this, $Ice__t_ProxyUnmarshalException);
        }
    }

    $Ice__t_ProxyUnmarshalException = IcePHP_defineException('::Ice::ProxyUnmarshalException', 'Ice_ProxyUnmarshalException', $Ice__t_MarshalException, null);
}

if(!class_exists('Ice_UnmarshalOutOfBoundsException'))
{
    class Ice_UnmarshalOutOfBoundsException extends Ice_MarshalException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::UnmarshalOutOfBoundsException';
        }

        public function __toString()
        {
            global $Ice__t_UnmarshalOutOfBoundsException;
            return IcePHP_stringifyException($this, $Ice__t_UnmarshalOutOfBoundsException);
        }
    }

    $Ice__t_UnmarshalOutOfBoundsException = IcePHP_defineException('::Ice::UnmarshalOutOfBoundsException', 'Ice_UnmarshalOutOfBoundsException', $Ice__t_MarshalException, null);
}

if(!class_exists('Ice_NoObjectFactoryException'))
{
    class Ice_NoObjectFactoryException extends Ice_MarshalException
    {
        public function __construct($reason='', $type='')
        {
            parent::__construct($reason);
            $this->type = $type;
        }

        public function ice_name()
        {
            return 'Ice::NoObjectFactoryException';
        }

        public function __toString()
        {
            global $Ice__t_NoObjectFactoryException;
            return IcePHP_stringifyException($this, $Ice__t_NoObjectFactoryException);
        }

        public $type;
    }

    $Ice__t_NoObjectFactoryException = IcePHP_defineException('::Ice::NoObjectFactoryException', 'Ice_NoObjectFactoryException', $Ice__t_MarshalException, array(
        array('type', $IcePHP__t_string)));
}

if(!class_exists('Ice_UnexpectedObjectException'))
{
    class Ice_UnexpectedObjectException extends Ice_MarshalException
    {
        public function __construct($reason='', $type='', $expectedType='')
        {
            parent::__construct($reason);
            $this->type = $type;
            $this->expectedType = $expectedType;
        }

        public function ice_name()
        {
            return 'Ice::UnexpectedObjectException';
        }

        public function __toString()
        {
            global $Ice__t_UnexpectedObjectException;
            return IcePHP_stringifyException($this, $Ice__t_UnexpectedObjectException);
        }

        public $type;
        public $expectedType;
    }

    $Ice__t_UnexpectedObjectException = IcePHP_defineException('::Ice::UnexpectedObjectException', 'Ice_UnexpectedObjectException', $Ice__t_MarshalException, array(
        array('type', $IcePHP__t_string),
    
        array('expectedType', $IcePHP__t_string)));
}

if(!class_exists('Ice_MemoryLimitException'))
{
    class Ice_MemoryLimitException extends Ice_MarshalException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::MemoryLimitException';
        }

        public function __toString()
        {
            global $Ice__t_MemoryLimitException;
            return IcePHP_stringifyException($this, $Ice__t_MemoryLimitException);
        }
    }

    $Ice__t_MemoryLimitException = IcePHP_defineException('::Ice::MemoryLimitException', 'Ice_MemoryLimitException', $Ice__t_MarshalException, null);
}

if(!class_exists('Ice_StringConversionException'))
{
    class Ice_StringConversionException extends Ice_MarshalException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::StringConversionException';
        }

        public function __toString()
        {
            global $Ice__t_StringConversionException;
            return IcePHP_stringifyException($this, $Ice__t_StringConversionException);
        }
    }

    $Ice__t_StringConversionException = IcePHP_defineException('::Ice::StringConversionException', 'Ice_StringConversionException', $Ice__t_MarshalException, null);
}

if(!class_exists('Ice_EncapsulationException'))
{
    class Ice_EncapsulationException extends Ice_MarshalException
    {
        public function __construct($reason='')
        {
            parent::__construct($reason);
        }

        public function ice_name()
        {
            return 'Ice::EncapsulationException';
        }

        public function __toString()
        {
            global $Ice__t_EncapsulationException;
            return IcePHP_stringifyException($this, $Ice__t_EncapsulationException);
        }
    }

    $Ice__t_EncapsulationException = IcePHP_defineException('::Ice::EncapsulationException', 'Ice_EncapsulationException', $Ice__t_MarshalException, null);
}

if(!class_exists('Ice_FeatureNotSupportedException'))
{
    class Ice_FeatureNotSupportedException extends Ice_LocalException
    {
        public function __construct($unsupportedFeature='')
        {
            $this->unsupportedFeature = $unsupportedFeature;
        }

        public function ice_name()
        {
            return 'Ice::FeatureNotSupportedException';
        }

        public function __toString()
        {
            global $Ice__t_FeatureNotSupportedException;
            return IcePHP_stringifyException($this, $Ice__t_FeatureNotSupportedException);
        }

        public $unsupportedFeature;
    }

    $Ice__t_FeatureNotSupportedException = IcePHP_defineException('::Ice::FeatureNotSupportedException', 'Ice_FeatureNotSupportedException', null, array(
        array('unsupportedFeature', $IcePHP__t_string)));
}

if(!class_exists('Ice_SecurityException'))
{
    class Ice_SecurityException extends Ice_LocalException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'Ice::SecurityException';
        }

        public function __toString()
        {
            global $Ice__t_SecurityException;
            return IcePHP_stringifyException($this, $Ice__t_SecurityException);
        }

        public $reason;
    }

    $Ice__t_SecurityException = IcePHP_defineException('::Ice::SecurityException', 'Ice_SecurityException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!class_exists('Ice_FixedProxyException'))
{
    class Ice_FixedProxyException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::FixedProxyException';
        }

        public function __toString()
        {
            global $Ice__t_FixedProxyException;
            return IcePHP_stringifyException($this, $Ice__t_FixedProxyException);
        }
    }

    $Ice__t_FixedProxyException = IcePHP_defineException('::Ice::FixedProxyException', 'Ice_FixedProxyException', null, null);
}

if(!class_exists('Ice_ResponseSentException'))
{
    class Ice_ResponseSentException extends Ice_LocalException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'Ice::ResponseSentException';
        }

        public function __toString()
        {
            global $Ice__t_ResponseSentException;
            return IcePHP_stringifyException($this, $Ice__t_ResponseSentException);
        }
    }

    $Ice__t_ResponseSentException = IcePHP_defineException('::Ice::ResponseSentException', 'Ice_ResponseSentException', null, null);
}
?>
