<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Plugin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once 'Ice/LoggerF.php';
require_once 'Ice/BuiltinSequences.php';

if(!interface_exists('Ice_Plugin'))
{
    interface Ice_Plugin
    {
        public function initialize();
        public function destroy();
    }

    $Ice__t_Plugin = IcePHP_defineClass('::Ice::Plugin', 'Ice_Plugin', true, $Ice__t_Object, null, null);
}

if(!interface_exists('Ice_PluginManager'))
{
    interface Ice_PluginManager
    {
        public function initializePlugins();
        public function getPlugins();
        public function getPlugin($name);
        public function addPlugin($name, $pi);
        public function destroy();
    }

    $Ice__t_PluginManager = IcePHP_defineClass('::Ice::PluginManager', 'Ice_PluginManager', true, $Ice__t_Object, null, null);
}
?>
