<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `PropertiesF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!isset($Ice__t_Properties))
{
    $Ice__t_Properties = IcePHP_declareClass('::Ice::Properties');
}

if(!isset($Ice__t_PropertiesAdmin))
{
    $Ice__t_PropertiesAdmin = IcePHP_declareClass('::Ice::PropertiesAdmin');
    $Ice__t_PropertiesAdminPrx = IcePHP_defineProxy($Ice__t_PropertiesAdmin);
}
?>
